#!/bin/bash
BASEDIR="$(dirname "$0")"

# Paths to planner components
TRANSLATE="$BASEDIR/../translate-old/translate.py" ##change
PREPROCESS="$BASEDIR/../preprocess-old/preprocess" ##change
SEARCH="$BASEDIR/release-search"


if [ $# -ne 3 ]; then
	echo "Usage: "$0" <domain_file> <problem_file> <result_file>"
	exit 1
else
    if [ ! -f "$BASEDIR"/../../output-old ] || [ ! -f ./output-old ]; then
            echo "1. Running translator"
            python2.7 "$TRANSLATE" "$1" "$2"
            echo "2. Running preprocessor"
            "$PREPROCESS" < output-old.sas
	        echo "3. Running search"
            "$SEARCH" "fFiR2011" "$3" < output-old
     else
	        echo "3. Running search"
	        "$SEARCH" "fFiR2011" "$3" < output-old
	fi
fi
