;; copyright (c) 2002-2015 Franz Inc, Oakland, CA - All rights reserved.
;;
;; The software, data and information contained herein are proprietary
;; to, and comprise valuable trade secrets of, Franz, Inc.  They are
;; given in confidence by Franz, Inc. pursuant to a written license
;; agreement, and may be stored and used only in accordance with the terms
;; of such license.
;;
;; Restricted Rights Legend
;; ------------------------
;; Use, duplication, and disclosure of the software, data and information
;; contained herein by any agency, department or entity of the U.S.
;; Government are subject to restrictions of Restricted Rights for
;; Commercial Software developed at private expense as specified in
;; DOD FAR Supplement 52.227-7013 (c) (1) (ii), as applicable.
;;
;; $Id: cg-obsolete.cl,v 1.3 2007/04/17 21:32:27 layer Exp $

((white-bitmap white-texture)
 (black-bitmap black-texture)
 (grey-bitmap gray-texture)
 (gray-bitmap gray-texture)
 (light-grey-bitmap light-gray-texture)
 (light-gray-bitmap light-gray-texture)
 (dark-grey-bitmap dark-gray-texture)
 (dark-gray-bitmap dark-gray-texture)
 (grey-texture gray-texture)
 (light-grey-texture light-gray-texture)
 (dark-grey-texture dark-gray-texture)
 (grey gray)
 (pixel-map-p texture-p)
 (make-pixel-map (make-instance 'texture)(make-instance 'pixmap))
 (pixel-map-ref contents-ref)
 (pixel-map-set contents-set)
 (colorize-bitmap colorize)
 (open-texture create-pixmap-handle)
 (close-texture destroy-pixmap-handle)
 (make-cursor (make-instance 'cursor))
 (open-cursor (make-instance 'cursor))
 (reflect-pixel-map-in-x reflect-pixmap-in-x)
 (reflect-pixel-map-in-y reflect-pixmap-in-y)
 (pop-up-dialog pop-up-modal-dialog)
 (*screen* (screen *system*))
 (*lisp-frame-window* (development-main-window *system*))
 (*lisp-main-window* (development-main-window *system*))
 (*window-exteriors* (window-configurations (configuration *ide-system*)))
 (closed-pixmap outline-item-closed-pixmap)
 (leaf-pixmap outline-item-leaf-pixmap)
 (opened-pixmap outline-item-opened-pixmap)
 (object-name name)
 (set-object-name (setf name))
 (stream-title title)
 (set-stream-title (setf title))
 (dialog-item-title title)
 (set-dialog-item-title (setf title))
 (dialog-item-value value)
 (set-dialog-item-value (setf value))
 (dialog-item-value-equality-test on-change-test)
 (set-dialog-item-value-equality-test (setf on-change-test))
 (dialog-item-range range)
 (set-dialog-item-range (setf range))
 (dialog-item-range-equality-test range-equality-test)
 (set-font (setf font))
 (dialog-item-font font)
 (set-dialog-item-font (setf font))
 (dialog-item-box box)
 (set-dialog-item-box (setf box))
 (dialog-item-set-range-fn on-range-change)
 (dialog-item-mouse-in-fn on-mouse-in)
 (dialog-item-mouse-out-fn on-mouse-out)
 (dialog-item-dialog-units-p dialog-units-p)
 (dialog-item-kill-focus-fn on-kill-focus)
 (dialog-item-set-focus-fn on-set-focus)
 (dialog-item-click-off click-off)
 (dialog-item-tabstop tabstop)
 (dialog-item-groupstart groupstart)
 (dialog-item-border border)
 (foreground-colour foreground-color)
 (set-foreground-colour (setf foreground-color))
 (outline-item-foreground-color foreground-color)
 (set-outline-item-foreground-color (setf foreground-color))
 (background-colour background-color)
 (set-background-color (setf background-color))
 (set-background-colour (setf background-color))
 (window-border border)
 (set-window-border (setf border))
 (set-background-texture (setf background-texture))
 (set-clipping-box (setf clipping-box))
 (animate-colour-number animate-color-number)
 (colour-number color-number)
 (set-color-number (setf color-number))
 (set-cursor (setf cursor))
 (set-cursor-position (setf cursor-position))
 (set-fill-texture (setf fill-texture))
 (set-fill-texture-origin (setf fill-texture-origin))
 (set-line-dashing (setf line-dashing))
 (set-line-height (setf line-height))
 (set-line-texture (setf line-texture))
 (set-line-width (setf line-width))
 (set-paint-operation (setf paint-operation))
 (set-palette (setf palette))
 (set-pixel (setf pixel))
 (set-pixel-x-y (setf pixel-x-y))
 (set-stream-origin (setf stream-origin))
 (timer-interval cg-timer-interval)
 (make-comtab (make-instance 'comtab))
 (dialog-item-dialog parent)
 (window-parent parent)
 (set-window-parent (setf parent))
 (dialog-item-window window)
 (window-state state)
 (tab-control-add-tab add-tab)
 (tab-control-remove-tab remove-tab)
 (tab-control-restore-tab restore-tab)
 (tab-control-row-count row-count)
 (set-tab-label (setf tab-label))
 (tab-control-rows-height rows-height)
 (tab-control-single-line-p single-line)
 (tab-control-fixed-width-p fixed-width)
 (tab-control-ragged-right-p ragged-right)
 (tab-control-button-style-p button-style)
 (tab-control-focus-on-click-p focus-on-click)
 (tab-control-set-tab-width (setf tab-width))
 (tab-control-set-tab-height (setf tab-height))
 (tab-control-set-fixed-width (setf fixed-width))
 (tab-control-set-single-line-p (setf single-line))
 (window-dialog-item dialog-item)
 (dialog-item-plist plist)
 (object-plist plist)
 (set-object-plist (setf plist))
 (stream-plist plist)
 (hotspot-name name)
 (hotspot-box box)
 (hotspot-parent parent)
 (hotspot-highlight-style highlight-style)
 (hotspot-available-p available)
 (outline-item-available-p available)
 (hotspot-color color)
 (hotspot-plist plist)
 (make-menu-item (make-instance 'menu-item))
 (menu-item-id name)
 (menu-item-menu menu)
 (set-menu-item-name (setf name))
 (menu-item-title title)
 (set-menu-item-title (setf title))
 (menu-item-selected-p selected)
 (set-menu-item-selected-p (setf selected))
 (menu-item-available-p available)
 (set-menu-item-available-p (setf available))
 (menu-item-font font)
 (set-menu-item-font (setf font))
 (menu-item-value value)
 (set-menu-item-value (setf value))
 (menu-item-event-synonym event-synonym)
 (set-menu-item-event-synonym (setf event-synonym))
 (menu-item-help-string help-string)
 (menu-item-plist plist)
 (window-menu menu)
 (set-window-menu (setf menu))
 (dialog-item-pressed-color-mapper pressed-color-mapper)
 (set-pressed-color-mapper (setf pressed-color-mapper))
 (dialog-item-stretching stretching)
 (widget-tab-control-spec tab-control)
 (set-widget-tab-control-spec (setf tab-control))
 (widget-tab-control tab-control-widget)
 (tab-control-remove-widget remove-component-from-tab)
 (tab-control-add-widget add-component-to-tab)
 (dialog-item-widget type-of)
 (object-package-name form-package-name)
 (set-object-package (setf form-package-name))
 (window-handle handle)
 (window-toolbars toolbars)
 (add-toolbar-to-window add-toolbar)
 (remove-toolbar-from-window remove-toolbar)
 (window-status-bar status-bar)
 (remove-status-bar-from-window remove-status-bar)
 (add-status-bar-to-window add-status-bar)
 (add-common-status-bar-to-window add-common-status-bar)
 (nwindow-exterior-top-left nexterior-top-left)
 (reshape-window-exterior (setf exterior))
 (window-exterior-top-left exterior-top-left)
 (window-exterior-width exterior-width)
 (window-exterior-height exterior-height)
 (nwindow-exterior nexterior)
 (window-exterior exterior)
 (nwindow-interior-top-left ninterior-top-left)
 (window-interior-top-left interior-top-left)
 (window-interior-width interior-width)
 (window-interior-height interior-height)
 (nwindow-interior ninterior)
 (window-interior interior)
 (reshape-window-interior (setf interior))
 (default-window-width default-width)
 (default-window-height default-height)
 (window-track-limits track-limits)
 (window-user-scrollable scrollbars)
 (set-window-user-scrollable (setf scrollbars))
 (window-user-shrinkable minimize-button)
 (set-window-user-shrinkable (setf minimize-button))
 (window-overlapped overlapped (not child-p))
 (draw-focus-p draw-focus)
 (retain-scroll-arrows-always-p retain-scroll-arrows-always)
 (use-default-tooltips-p use-default-tooltips)
 (recessed-p recessed)
 (button-3d-border-p button-3d-border)
 (button-black-border-p button-black-border)
 (multiple-selections-p multiple-selections)
 (window-icon icon)
 (set-window-icon (setf icon))
 (window-attachment attachment)
 (window-immediate-children windows)
 (window-modified-p modified)
 (get-window-text get-text)
 (get-widget-text get-text)
 (window-user-movable title-bar)
 (set-window-user-movable (setf title-bar))
 (window-user-closable close-button)
 (set-window-user-closable (setf close-button))
 (window-user-resizable resizable)
 (set-window-user-resizable (setf resizable))
 (outline-sort-predicate on-sort-predicate)
 (column-sort-predicate on-sort-predicate)
 (column-font font)
 (outline-draw-icons-p draw-icons)
 (outline-draw-lines-p draw-lines)
 (outline-draw-plus-minus-p draw-plus-minus)
 (editable-in-place-p editable-in-place)
 (widget-orientation orientation)
 (bury-widget bury-component)
 (expose-widget expose-component)
 (add-widget add-component)
 (remove-widget remove-component)
 (focus-widget focus-component)
 (set-focus-widget set-focus-component)
 (tab-to-next-widget tab-to-next)
 (invalidate-widget invalidate)
 (invalidate-widget-nc invalidate)
 (trackbar-tick-side tick-side)
 (trackbar-tick-frequency tick-frequency)
 (trackbar-value-range-p select-range)
 (trackbar-value-range visible-range)
 (trackbar-no-pointer-p no-pointer)
 (trackbar-increment increment)
 (trackbar-tick-position tick-position)
 (status-bar-parts parts)
 (set-status-bar-parts (setf parts))
 (status-bar-simple-mode-p simple-mode)
 (set-status-bar-simple-mode-p (setf simple-mode))
 (single-line-p single-line)
 (up-down-control-increment increment)
 (up-down-control-buddy-widget buddy-widget)
 (up-down-control-orientation orientation)
 (up-down-control-buddy-side buddy-side)
 (up-down-control-wrapping-p wrapping)
 (make-header-info (make-instance 'header-info))
 (widget find-component)
 (find-widget find-component)
 (menu-selection-function on-click)
 (menu-justify justification)
 (menu-rows rows)
 (menu-columns columns)
 (make-tab-info (make-instance 'tab-info))
 (tab-info-id name)
 (tab-info-label label)
 (tab-info-cached-widgets dialog-items)
 (tab-info-tab-control tab-control)
 (tab-info-index index)
 (make-outline-item (make-instance 'outline-item))
 (outline-item-available available)
 (set-outline-item-available (setf available))
 (outline-item-background-color background-color)
 (set-outline-item-background-color (setf background-color))
 (index-from-item-value index-from-outline-item-value)
 (outline-item-font font)
 (set-outline-item-font (setf font))
 (outline-item-plist plist)
 (set-outline-item-plist (setf plist))
 (outline-item-selected-p selected)
 (set-outline-item-selected-p (setf selected))
 (outline-item-state state)
 (set-outline-item-state (setf state))
 (outline-item-subitems range)
 (set-outline-item-subitems (setf range))
 (outline-item-type kind)
 (set-outline-item-type (setf kind))
 (outline-item-value value)
 (set-outline-item-value (setf value))
 (outline-item find-outline-item)
 (subitems-on-open range-on-open)
 (subitems-on-close range-on-close)
 (outline-change-value-availability
  change-outline-item-value-availability)
 (outline-change-item-availability change-outline-item-availability)
 (tab-control-tab find-tab)
 (make-dialog-item (make-instance 'dialog-item))
 (close-dialog-item close)
 (outline-close-value close-outline-item-value)
 (outline-open-value open-outline-item-value)
 (outline-add-value add-outline-item-value)
 (outline-add-item add-outline-item)
 (outline-remove-value remove-outline-item-value)
 (outline-replace-item-value replace-outline-item-value)
 (outline-move-value move-outline-item-value)
 (outline-focus-index focus-index)
 (outline-tabs tabs)
 (outline-right-justification-width right-justification-width)
 (outline-indentation indentation)
 (outline-select-on-open-p select-on-open)
 (outline-opened-pixmap default-opened-pixmap)
 (outline-closed-pixmap default-closed-pixmap)
 (outline-leaf-pixmap default-leaf-pixmap)
 (button-image pixmap)
 (button-string title)
 (button-width width)
 (button-height height)
 (section-available-p available)
 (cell-and-sections-available-p cell-and-sections-available)
 (available-p-reader available-reader)
 (section-selected-p selected)
 (selected-p-reader selected-reader)
 (section-selectable-p selectable)
 (section-deletable-p deletable)
 (section-movable-p movable)
 (section-resizable-p resizable)
 (section-proportional-p proportional)
 (section-scrollable-p scrollbars)
 (section-border-color border-color)
 (section-border-width border-width)
 (section-border-dashing border-dashing)
 (section-name name)
 (section-parent parent)
 (section-scroll-pos scroll-position)
 (empty-section-color empty-color)
 (min-section-size minimum-size)
 (section-size size)
 (section-siblings siblings)
 (section-sibling find-sibling)
 (sibling find-sibling)
 (section-pos edge-position)
 (column-sortable-p sortable)
 (set-right-margin (setf right-margin))
 (set-top-margin (setf top-margin))
 (set-left-margin (setf left-margin))
 (set-bottom-margin (setf bottom-margin))
 (set-page-width (setf page-width))
 (set-page-height (setf page-height))
 (pop-up-p pop-up)
 (scrollable-p scrollbars)
 (grid-border-color border-color)
 (grid-sort-descending-p sort-reverse)
 (dialog-item-set-value-fn on-change)
 (dialog-item-available-p available)
 (set-dialog-item-available-p (setf available))
 (safe-read-from-string read-from-string-safely)
 (invalidate-object invalidate)
 (pop-up-right-button-menu pop-up-shortcut-menu)
 (object-name-string name-string)
 (grid-border-width border-width)
 (header-control-add-header add-header)
 (header-control-button-style-p button-style)
 (header-fill-p header-fill-space)
 (pop-up-letterred-menu pop-up-lettered-menu)
 (window-read-only-p read-only)
 (header-control-header header)
 (list-widget-column-width column-width)
 (list-widget-set-column-width (object value))
 (*lisp-clipboard-limit* 
   (clipboard-history-limit (configuration *system*)))
 (pop-up-save-file-dialog ask-user-for-existing-pathname)
 (pop-up-open-file-dialog ask-user-for-existing-pathname)
 (open-dialog make-window)
 (background-mode transparent-character-background)
 (set-background-mode (setf transparent-character-background))
 (initialize-dialog-item-value initialize-value)
 (modal-dialog modal-window)
 (lisp-main-window development-main-window)
 (*lisp-status-bar-number-of-lines*
  *status-bar-number-of-lines*)
 (*default-window-width-factor* 
  (default-width-factor (configuration *system*)))
 (*default-window-height-factor* 
  (default-height-factor (configuration *system*)))
 (*default-window-width* 
  (default-width (configuration *system*)))
 (*default-window-height* 
  (default-height (configuration *system*)))
 (*short-site-name* (short-site-name))
 (*long-site-name* (long-site-name))
 (*user-name* (sys:user-name))
 (*machine-instance* (machine-instance))
 (*comment-indent* (comment-indent (configuration *ide-system*)))
 (*flash-how-often* (parenthesis-matching-style (configuration *system*)))
 (*min-pixels-between-widgets* 
  (min-pixels-between-widgets (configuration *ide-system*)))
 (*editor-font* (editor-font (configuration *ide-system*)))
 (*class-graph-initial-depth* 
  (class-graph-initial-depth (configuration *ide-system*)))
 (*top-font* (debug-font (configuration *ide-system*)))
 (*class-graph-font* 
  (class-graph-font (configuration *ide-system*)))
 (*hinst* (hinst (app *system*)))
 (*tooltip-delay* (tooltip-delay (configuration *system*)))
 (*show-tooltips* (show-tooltips (configuration *system*)))
 (*tooltip-vertical-offset*
  (tooltip-vertical-offset (configuration *system*)))
 (*default-opened-pixmap* 
  (texture (find-pixmap :default-opened)))
 (*default-closed-pixmap* 
  (texture (find-pixmap :default-closed)))
 (*default-leaf-pixmap* 
  (texture (find-pixmap :default-leaf)))
 (*unavailable-color-mapper* (unavailable-color-mapper object))
 (*default-palette-vector* (default-pixmap-color-vector))
 (*top-may-exit-tests* (exit-tests *system*))
 (*tooltip-font* (tooltip-font))
 (*status-bar-font* (status-bar-font window))
 (*lisp-status-bar-font* (status-bar-font window))
 (*top-prompt* tpl:*prompt*)
 (*lisp-message-print-length*
  (lisp-message-print-length (configuration *ide-system*)))
 (*lisp-message-print-level*
  (lisp-message-print-level (configuration *ide-system*)))
 (header-control-remove-header remove-header)
 (*default-printer-font-face*
  (font-face (printer-font (configuration *ide-system*))))
 (*default-printer-font-size*
  (font-size (printer-font (configuration *ide-system*))))
 (*default-tab-height* (default-tab-height (configuration *system*)))
 (*default-tab-width* (default-tab-width (configuration *system*)))
 (*offset-from-selected-window* 
  (offset-from-selected-window (configuration *system*))))
