(define (problem pfile22-ma) (:domain depots)
  (:objects hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 hoist6 hoist7 hoist8 hoist9 hoist10 hoist11 hoist12 hoist13 hoist14 - hoist
             crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 crate10 crate11 crate12 crate13 crate14 crate15 crate16 crate17 crate18 crate19 - crate
             pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 pallet6 pallet7 pallet8 pallet9 pallet10 pallet11 pallet12 pallet13 pallet14 pallet15 pallet16 pallet17 pallet18 pallet19 - pallet
             truck1 - truck
             distributor0 distributor1 distributor2 distributor3 distributor4 distributor5 - distributor
             depot0 depot1 depot2 depot3 depot4 depot5 - depot
            )
  (:init
       (at pallet0 depot0)
       (clear crate10)
       (at pallet1 depot1)
       (clear crate17)
       (at pallet2 depot2)
       (clear pallet2)
       (at pallet3 depot3)
       (clear pallet3)
       (at pallet4 depot4)
       (clear pallet4)
       (at pallet5 depot5)
       (clear crate8)
       (at pallet6 distributor0)
       (clear pallet6)
       (at pallet7 distributor1)
       (clear crate19)
       (at pallet8 distributor2)
       (clear crate13)
       (at pallet9 distributor3)
       (clear crate16)
       (at pallet10 distributor4)
       (clear crate14)
       (at pallet11 distributor5)
       (clear crate0)
       (at pallet12 distributor4)
       (clear crate18)
       (at pallet13 distributor2)
       (clear crate15)
       (at pallet14 depot3)
       (clear pallet14)
       (at pallet15 depot3)
       (clear pallet15)
       (at pallet16 distributor1)
       (clear pallet16)
       (at pallet17 distributor2)
       (clear crate6)
       (at pallet18 distributor3)
       (clear pallet18)
       (at pallet19 distributor1)
       (clear pallet19)
       (at-truck truck1 distributor4)
       (at-hoist hoist0 depot0)
       (available hoist0)
       (at-hoist hoist1 depot1)
       (available hoist1)
       (at-hoist hoist2 depot2)
       (available hoist2)
       (at-hoist hoist3 depot3)
       (available hoist3)
       (at-hoist hoist4 depot4)
       (available hoist4)
       (at-hoist hoist5 depot5)
       (available hoist5)
       (at-hoist hoist6 distributor0)
       (available hoist6)
       (at-hoist hoist7 distributor1)
       (available hoist7)
       (at-hoist hoist8 distributor2)
       (available hoist8)
       (at-hoist hoist9 distributor3)
       (available hoist9)
       (at-hoist hoist10 distributor4)
       (available hoist10)
       (at-hoist hoist11 distributor5)
       (available hoist11)
       (at-hoist hoist12 depot0)
       (available hoist12)
       (at-hoist hoist13 depot5)
       (available hoist13)
       (at-hoist hoist14 depot5)
       (available hoist14)
       (at crate0 distributor5)
       (on crate0 pallet11)
       (at crate1 depot0)
       (on crate1 pallet0)
       (at crate2 distributor4)
       (on crate2 pallet10)
       (at crate3 distributor2)
       (on crate3 pallet8)
       (at crate4 distributor1)
       (on crate4 pallet7)
       (at crate5 distributor4)
       (on crate5 crate2)
       (at crate6 distributor2)
       (on crate6 pallet17)
       (at crate7 depot5)
       (on crate7 pallet5)
       (at crate8 depot5)
       (on crate8 crate7)
       (at crate9 depot0)
       (on crate9 crate1)
       (at crate10 depot0)
       (on crate10 crate9)
       (at crate11 distributor3)
       (on crate11 pallet9)
       (at crate12 depot1)
       (on crate12 pallet1)
       (at crate13 distributor2)
       (on crate13 crate3)
       (at crate14 distributor4)
       (on crate14 crate5)
       (at crate15 distributor2)
       (on crate15 pallet13)
       (at crate16 distributor3)
       (on crate16 crate11)
       (at crate17 depot1)
       (on crate17 crate12)
       (at crate18 distributor4)
       (on crate18 pallet12)
       (at crate19 distributor1)
       (on crate19 crate4))
  (:goal (and 
       (on crate7 pallet5))))