(define (problem pfile19-ma) (:domain depots)
  (:objects hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 hoist6 hoist7 - hoist
             crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 - crate
             pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 pallet6 pallet7 pallet8 pallet9 - pallet
             truck3 - truck
             distributor0 distributor1 distributor2 distributor3 - distributor
             depot0 depot1 depot2 depot3 - depot
            )
  (:init
       (at pallet0 depot0)
       (clear crate6)
       (at pallet1 depot1)
       (clear crate1)
       (at pallet2 depot2)
       (clear pallet2)
       (at pallet3 depot3)
       (clear crate7)
       (at pallet4 distributor0)
       (clear crate2)
       (at pallet5 distributor1)
       (clear crate5)
       (at pallet6 distributor2)
       (clear pallet6)
       (at pallet7 distributor3)
       (clear pallet7)
       (at pallet8 distributor2)
       (clear crate4)
       (at pallet9 depot3)
       (clear crate0)
       (at-truck truck3 distributor3)
       (at-hoist hoist0 depot0)
       (available hoist0)
       (at-hoist hoist1 depot1)
       (available hoist1)
       (at-hoist hoist2 depot2)
       (available hoist2)
       (at-hoist hoist3 depot3)
       (available hoist3)
       (at-hoist hoist4 distributor0)
       (available hoist4)
       (at-hoist hoist5 distributor1)
       (available hoist5)
       (at-hoist hoist6 distributor2)
       (available hoist6)
       (at-hoist hoist7 distributor3)
       (available hoist7)
       (at crate0 depot3)
       (on crate0 pallet9)
       (at crate1 depot1)
       (on crate1 pallet1)
       (at crate2 distributor0)
       (on crate2 pallet4)
       (at crate3 distributor1)
       (on crate3 pallet5)
       (at crate4 distributor2)
       (on crate4 pallet8)
       (at crate5 distributor1)
       (on crate5 crate3)
       (at crate6 depot0)
       (on crate6 pallet0)
       (at crate7 depot3)
       (on crate7 pallet3))
  (:goal (and )))