#!/bin/sh

cd "$(dirname "$0")"
ROOT=$PWD


# Compile
cd $ROOT/VAL-4.2.08
make clean
make

if [ $? -ne 0 ]; then
	echo -e "\nCompilation error when compiling: VAL-4.2.08" 
	exit 1
fi

cd $ROOT/adl2strips
make clean
make

if [ $? -ne 0 ]; then
	echo -e "\nCompilation error when compiling: adl2strips" 
	exit 1
fi
