/*
  File : grid.idl
  Date : Sun Mar 22 00:51:40 PST 1998
  User : stiller
*/
module example {
  interface grid;
  interface grid {
    readonly attribute short height;
    readonly attribute short width;
    void set(
      in short n,
      in short m,
      in string value
    );
    string get(
      in short n,
      in short m
    );
  };
};

