(define (problem depotprob985) (:domain depots)
(:objects
	depot0 depot1 depot2 depot3 - Depot
	distributor0 distributor1 distributor2 distributor3 - Distributor
	truck0 truck1 truck2 truck3 truck4 truck5 - Truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 pallet6 pallet7 pallet8 pallet9 - Pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 crate10 crate11 crate12 crate13 crate14 - Crate
	hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 hoist6 hoist7 - Hoist)
(:init
	(at pallet0 depot0)
	(clear pallet0)
	(at pallet1 depot1)
	(clear pallet1)
	(at pallet2 depot2)
	(clear crate7)
	(at pallet3 depot3)
	(clear crate6)
	(at pallet4 distributor0)
	(clear crate9)
	(at pallet5 distributor1)
	(clear crate8)
	(at pallet6 distributor2)
	(clear crate11)
	(at pallet7 distributor3)
	(clear crate13)
	(at pallet8 depot0)
	(clear crate14)
	(at pallet9 depot3)
	(clear crate10)
	(at-truck truck0 distributor0)
	(at-truck truck1 distributor0)
	(at-truck truck2 distributor3)
	(at-truck truck3 distributor1)
	(at-truck truck4 distributor1)
	(at-truck truck5 distributor3)
	(at-hoist hoist0 depot0)
	(available hoist0)
	(at-hoist hoist1 depot1)
	(available hoist1)
	(at-hoist hoist2 depot2)
	(available hoist2)
	(at-hoist hoist3 depot3)
	(available hoist3)
	(at-hoist hoist4 distributor0)
	(available hoist4)
	(at-hoist hoist5 distributor1)
	(available hoist5)
	(at-hoist hoist6 distributor2)
	(available hoist6)
	(at-hoist hoist7 distributor3)
	(available hoist7)
	(at crate0 distributor3)
	(on crate0 pallet7)
	(at crate1 depot3)
	(on crate1 pallet3)
	(at crate2 distributor3)
	(on crate2 crate0)
	(at crate3 depot2)
	(on crate3 pallet2)
	(at crate4 depot3)
	(on crate4 pallet9)
	(at crate5 distributor2)
	(on crate5 pallet6)
	(at crate6 depot3)
	(on crate6 crate1)
	(at crate7 depot2)
	(on crate7 crate3)
	(at crate8 distributor1)
	(on crate8 pallet5)
	(at crate9 distributor0)
	(on crate9 pallet4)
	(at crate10 depot3)
	(on crate10 crate4)
	(at crate11 distributor2)
	(on crate11 crate5)
	(at crate12 depot0)
	(on crate12 pallet8)
	(at crate13 distributor3)
	(on crate13 crate2)
	(at crate14 depot0)
	(on crate14 crate12)
)

(:goal (and
		(on crate1 crate13)
		(on crate2 pallet8)
		(on crate4 crate2)
		(on crate5 pallet7)
		(on crate6 crate7)
		(on crate7 pallet2)
		(on crate8 pallet4)
		(on crate9 pallet0)
		(on crate10 crate12)
		(on crate11 crate14)
		(on crate12 crate8)
		(on crate13 crate4)
		(on crate14 pallet1)
	)
))
