(define (problem depotprob24) (:domain depots)
(:objects
	depot0 depot1 depot2 depot3 - Depot
	distributor0 distributor1 distributor2 distributor3 - Distributor
	truck0 truck1 truck2 truck3 truck4 truck5 - Truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 pallet6 pallet7 pallet8 pallet9 - Pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 crate10 crate11 crate12 crate13 crate14 - Crate
	hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 hoist6 hoist7 - Hoist)
(:init
	(at pallet0 depot0)
	(clear crate8)
	(at pallet1 depot1)
	(clear crate1)
	(at pallet2 depot2)
	(clear crate12)
	(at pallet3 depot3)
	(clear pallet3)
	(at pallet4 distributor0)
	(clear crate3)
	(at pallet5 distributor1)
	(clear crate14)
	(at pallet6 distributor2)
	(clear crate13)
	(at pallet7 distributor3)
	(clear crate5)
	(at pallet8 depot3)
	(clear pallet8)
	(at pallet9 depot0)
	(clear crate7)
	(at-truck truck0 depot2)
	(at-truck truck1 distributor0)
	(at-truck truck2 distributor0)
	(at-truck truck3 depot3)
	(at-truck truck4 distributor1)
	(at-truck truck5 depot1)
	(at-hoist hoist0 depot0)
	(available hoist0)
	(at-hoist hoist1 depot1)
	(available hoist1)
	(at-hoist hoist2 depot2)
	(available hoist2)
	(at-hoist hoist3 depot3)
	(available hoist3)
	(at-hoist hoist4 distributor0)
	(available hoist4)
	(at-hoist hoist5 distributor1)
	(available hoist5)
	(at-hoist hoist6 distributor2)
	(available hoist6)
	(at-hoist hoist7 distributor3)
	(available hoist7)
	(at crate0 distributor2)
	(on crate0 pallet6)
	(at crate1 depot1)
	(on crate1 pallet1)
	(at crate2 depot0)
	(on crate2 pallet0)
	(at crate3 distributor0)
	(on crate3 pallet4)
	(at crate4 depot0)
	(on crate4 crate2)
	(at crate5 distributor3)
	(on crate5 pallet7)
	(at crate6 distributor2)
	(on crate6 crate0)
	(at crate7 depot0)
	(on crate7 pallet9)
	(at crate8 depot0)
	(on crate8 crate4)
	(at crate9 distributor2)
	(on crate9 crate6)
	(at crate10 depot2)
	(on crate10 pallet2)
	(at crate11 distributor2)
	(on crate11 crate9)
	(at crate12 depot2)
	(on crate12 crate10)
	(at crate13 distributor2)
	(on crate13 crate11)
	(at crate14 distributor1)
	(on crate14 pallet5)
)

(:goal (and
		(on crate0 crate14)
		(on crate1 pallet7)
		(on crate2 crate13)
		(on crate3 pallet0)
		(on crate4 crate7)
		(on crate5 pallet6)
		(on crate6 pallet4)
		(on crate7 crate5)
		(on crate8 crate9)
		(on crate9 crate0)
		(on crate10 pallet8)
		(on crate11 pallet2)
		(on crate12 crate8)
		(on crate13 crate1)
		(on crate14 pallet9)
	)
))
