(define (problem obfuscated-rover0-ipc3-pfile10) (:domain rover)
  (:objects rover1-camera3 rover1-camera2 rover1-camera1 rover1-camera0 - rover1-camera
             rover1-rover1store - rover1-store
             objective0 objective1 objective2 objective3 - objective
             waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 - waypoint
             rover0-rover0store - rover0-store
             rover1 rover0 - rover
             colour high_res low_res - mode
             general - lander
            )
  (:init
       (rover1-visible_from objective3 waypoint5)
       (rover1-visible_from objective3 waypoint4)
       (rover1-visible_from objective3 waypoint3)
       (rover1-visible_from objective3 waypoint2)
       (rover1-visible_from objective3 waypoint1)
       (rover1-visible_from objective3 waypoint0)
       (rover1-visible_from objective2 waypoint3)
       (rover1-visible_from objective2 waypoint2)
       (rover1-visible_from objective2 waypoint1)
       (rover1-visible_from objective2 waypoint0)
       (rover1-visible_from objective1 waypoint3)
       (rover1-visible_from objective1 waypoint2)
       (rover1-visible_from objective1 waypoint1)
       (rover1-visible_from objective1 waypoint0)
       (rover1-visible_from objective0 waypoint0)
       (rover1-supports rover1-camera3 low_res)
       (rover1-supports rover1-camera3 high_res)
       (rover1-calibration_target rover1-camera3 objective2)
       (rover1-on_board rover1-camera3)
       (rover1-supports rover1-camera2 low_res)
       (rover1-supports rover1-camera2 colour)
       (rover1-calibration_target rover1-camera2 objective1)
       (rover1-on_board rover1-camera2)
       (rover1-supports rover1-camera1 colour)
       (rover1-calibration_target rover1-camera1 objective3)
       (rover1-on_board rover1-camera1)
       (rover1-supports rover1-camera0 low_res)
       (rover1-calibration_target rover1-camera0 objective2)
       (rover1-on_board rover1-camera0)
       (rover1-can_traverse waypoint6 waypoint0)
       (rover1-can_traverse waypoint0 waypoint6)
       (rover1-can_traverse waypoint2 waypoint0)
       (rover1-can_traverse waypoint0 waypoint2)
       (rover1-can_traverse waypoint1 waypoint0)
       (rover1-can_traverse waypoint0 waypoint1)
       (rover1-equipped_for_imaging)
       (rover1-equipped_for_soil_analysis)
       (rover1-empty rover1-rover1store)
       (rover1-store_of rover1-rover1store)
       (rover1-available)
       (rover1-at waypoint0)
       (rover0-visible_from objective3 waypoint5)
       (rover0-visible_from objective3 waypoint4)
       (rover0-visible_from objective3 waypoint3)
       (rover0-visible_from objective3 waypoint2)
       (rover0-visible_from objective3 waypoint1)
       (rover0-visible_from objective3 waypoint0)
       (rover0-visible_from objective2 waypoint3)
       (rover0-visible_from objective2 waypoint2)
       (rover0-visible_from objective2 waypoint1)
       (rover0-visible_from objective2 waypoint0)
       (rover0-visible_from objective1 waypoint3)
       (rover0-visible_from objective1 waypoint2)
       (rover0-visible_from objective1 waypoint1)
       (rover0-visible_from objective1 waypoint0)
       (rover0-visible_from objective0 waypoint0)
       (rover0-can_traverse waypoint5 waypoint1)
       (rover0-can_traverse waypoint1 waypoint5)
       (rover0-can_traverse waypoint6 waypoint4)
       (rover0-can_traverse waypoint4 waypoint6)
       (rover0-can_traverse waypoint3 waypoint4)
       (rover0-can_traverse waypoint4 waypoint3)
       (rover0-can_traverse waypoint2 waypoint4)
       (rover0-can_traverse waypoint4 waypoint2)
       (rover0-can_traverse waypoint1 waypoint4)
       (rover0-can_traverse waypoint4 waypoint1)
       (rover0-can_traverse waypoint0 waypoint4)
       (rover0-can_traverse waypoint4 waypoint0)
       (rover0-equipped_for_rock_analysis)
       (rover0-equipped_for_soil_analysis)
       (rover0-empty rover0-rover0store)
       (rover0-store_of rover0-rover0store)
       (rover0-available)
       (rover0-at waypoint4)
       (channel_free general)
       (at_lander general waypoint1)
       (at_rock_sample waypoint6)
       (at_soil_sample waypoint6)
       (at_rock_sample waypoint4)
       (at_soil_sample waypoint4)
       (at_rock_sample waypoint3)
       (at_soil_sample waypoint3)
       (at_rock_sample waypoint1)
       (at_rock_sample waypoint0)
       (at_soil_sample waypoint0)
       (visible waypoint4 waypoint6)
       (visible waypoint6 waypoint4)
       (visible waypoint6 waypoint5)
       (visible waypoint5 waypoint6)
       (visible waypoint0 waypoint5)
       (visible waypoint5 waypoint0)
       (visible waypoint3 waypoint4)
       (visible waypoint4 waypoint3)
       (visible waypoint1 waypoint4)
       (visible waypoint4 waypoint1)
       (visible waypoint0 waypoint4)
       (visible waypoint4 waypoint0)
       (visible waypoint5 waypoint3)
       (visible waypoint3 waypoint5)
       (visible waypoint6 waypoint2)
       (visible waypoint2 waypoint6)
       (visible waypoint4 waypoint2)
       (visible waypoint2 waypoint4)
       (visible waypoint0 waypoint2)
       (visible waypoint2 waypoint0)
       (visible waypoint5 waypoint1)
       (visible waypoint1 waypoint5)
       (visible waypoint2 waypoint1)
       (visible waypoint1 waypoint2)
       (visible waypoint0 waypoint1)
       (visible waypoint1 waypoint0)
       (visible waypoint6 waypoint0)
       (visible waypoint0 waypoint6))
  (:goal (and 
       (communicated_rock_data waypoint1)
       (communicated_rock_data waypoint0)
       (communicated_rock_data waypoint3)
       (communicated_rock_data waypoint4)
       (communicated_soil_data waypoint4)
       (communicated_soil_data waypoint3)
       (communicated_soil_data waypoint6)
       (communicated_image_data objective3 low_res)
       (communicated_image_data objective2 colour)
       (communicated_image_data objective3 colour)
       (communicated_soil_data waypoint0))))