(define (problem ipc3-pfile13) (:domain rover)
  (:objects objective0 objective1 objective2 objective3 - objective
             camera0 camera1 - camera
             waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 - waypoint
             rover2store - store
             rover2 - rover
             colour high_res low_res - mode
             general - lander
            )
  (:init
       (visible waypoint0 waypoint1)
       (visible waypoint1 waypoint0)
       (visible waypoint0 waypoint3)
       (visible waypoint3 waypoint0)
       (visible waypoint0 waypoint5)
       (visible waypoint5 waypoint0)
       (visible waypoint0 waypoint6)
       (visible waypoint6 waypoint0)
       (visible waypoint1 waypoint2)
       (visible waypoint2 waypoint1)
       (visible waypoint1 waypoint3)
       (visible waypoint3 waypoint1)
       (visible waypoint1 waypoint4)
       (visible waypoint4 waypoint1)
       (visible waypoint1 waypoint5)
       (visible waypoint5 waypoint1)
       (visible waypoint1 waypoint7)
       (visible waypoint7 waypoint1)
       (visible waypoint1 waypoint8)
       (visible waypoint8 waypoint1)
       (visible waypoint2 waypoint0)
       (visible waypoint0 waypoint2)
       (visible waypoint2 waypoint4)
       (visible waypoint4 waypoint2)
       (visible waypoint2 waypoint6)
       (visible waypoint6 waypoint2)
       (visible waypoint3 waypoint4)
       (visible waypoint4 waypoint3)
       (visible waypoint3 waypoint7)
       (visible waypoint7 waypoint3)
       (visible waypoint4 waypoint0)
       (visible waypoint0 waypoint4)
       (visible waypoint5 waypoint2)
       (visible waypoint2 waypoint5)
       (visible waypoint5 waypoint3)
       (visible waypoint3 waypoint5)
       (visible waypoint7 waypoint0)
       (visible waypoint0 waypoint7)
       (visible waypoint7 waypoint2)
       (visible waypoint2 waypoint7)
       (visible waypoint7 waypoint6)
       (visible waypoint6 waypoint7)
       (visible waypoint8 waypoint2)
       (visible waypoint2 waypoint8)
       (visible waypoint8 waypoint3)
       (visible waypoint3 waypoint8)
       (visible waypoint8 waypoint4)
       (visible waypoint4 waypoint8)
       (visible waypoint8 waypoint7)
       (visible waypoint7 waypoint8)
       (at_rock_sample waypoint0)
       (at_rock_sample waypoint1)
       (at_soil_sample waypoint2)
       (at_rock_sample waypoint2)
       (at_soil_sample waypoint4)
       (at_rock_sample waypoint4)
       (at_soil_sample waypoint5)
       (at_rock_sample waypoint6)
       (at_soil_sample waypoint7)
       (at_rock_sample waypoint7)
       (at_rock_sample waypoint8)
       (at_lander general waypoint2)
       (channel_free general)
       (at rover2 waypoint6)
       (available rover2)
       (store_of rover2store rover2)
       (empty rover2store)
       (equipped_for_soil_analysis rover2)
       (equipped_for_rock_analysis rover2)
       (equipped_for_imaging rover2)
       (can_traverse rover2 waypoint6 waypoint0)
       (can_traverse rover2 waypoint0 waypoint6)
       (can_traverse rover2 waypoint6 waypoint2)
       (can_traverse rover2 waypoint2 waypoint6)
       (can_traverse rover2 waypoint6 waypoint7)
       (can_traverse rover2 waypoint7 waypoint6)
       (can_traverse rover2 waypoint0 waypoint1)
       (can_traverse rover2 waypoint1 waypoint0)
       (can_traverse rover2 waypoint0 waypoint3)
       (can_traverse rover2 waypoint3 waypoint0)
       (can_traverse rover2 waypoint0 waypoint4)
       (can_traverse rover2 waypoint4 waypoint0)
       (can_traverse rover2 waypoint0 waypoint5)
       (can_traverse rover2 waypoint5 waypoint0)
       (can_traverse rover2 waypoint2 waypoint8)
       (can_traverse rover2 waypoint8 waypoint2)
       (on_board camera0 rover2)
       (calibration_target camera0 objective1)
       (supports camera0 colour)
       (supports camera0 high_res)
       (on_board camera1 rover2)
       (calibration_target camera1 objective1)
       (supports camera1 colour)
       (supports camera1 low_res)
       (visible_from objective0 waypoint0)
       (visible_from objective1 waypoint0)
       (visible_from objective1 waypoint1)
       (visible_from objective1 waypoint2)
       (visible_from objective1 waypoint3)
       (visible_from objective1 waypoint4)
       (visible_from objective1 waypoint5)
       (visible_from objective1 waypoint6)
       (visible_from objective1 waypoint7)
       (visible_from objective2 waypoint0)
       (visible_from objective2 waypoint1)
       (visible_from objective2 waypoint2)
       (visible_from objective2 waypoint3)
       (visible_from objective2 waypoint4)
       (visible_from objective2 waypoint5)
       (visible_from objective3 waypoint0)
       (visible_from objective3 waypoint1)
       (visible_from objective3 waypoint2)
       (visible_from objective3 waypoint3)
       (visible_from objective3 waypoint4)
       (visible_from objective3 waypoint5)
       (visible_from objective3 waypoint6)
       (visible_from objective3 waypoint7))
  (:goal (and 
       (communicated_image_data objective2 high_res)
       (communicated_image_data objective1 high_res)
       (communicated_image_data objective3 high_res)
       (communicated_rock_data waypoint1)
       (communicated_rock_data waypoint8)
       (communicated_rock_data waypoint7)
       (communicated_rock_data waypoint6)
       (communicated_rock_data waypoint4)
       (communicated_soil_data waypoint4)
       (communicated_soil_data waypoint2)
       (communicated_soil_data waypoint5)
       (communicated_soil_data waypoint7))))