(define (problem ipc3-pfile08) (:domain rover)
  (:objects objective0 objective1 objective2 - objective
             waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 - waypoint
             rover0store - store
             rover0 - rover
             colour high_res low_res - mode
             general - lander
            )
  (:init
       (visible waypoint0 waypoint1)
       (visible waypoint1 waypoint0)
       (visible waypoint0 waypoint3)
       (visible waypoint3 waypoint0)
       (visible waypoint1 waypoint5)
       (visible waypoint5 waypoint1)
       (visible waypoint2 waypoint0)
       (visible waypoint0 waypoint2)
       (visible waypoint2 waypoint1)
       (visible waypoint1 waypoint2)
       (visible waypoint2 waypoint3)
       (visible waypoint3 waypoint2)
       (visible waypoint2 waypoint4)
       (visible waypoint4 waypoint2)
       (visible waypoint3 waypoint4)
       (visible waypoint4 waypoint3)
       (visible waypoint3 waypoint5)
       (visible waypoint5 waypoint3)
       (visible waypoint4 waypoint0)
       (visible waypoint0 waypoint4)
       (visible waypoint4 waypoint1)
       (visible waypoint1 waypoint4)
       (visible waypoint5 waypoint2)
       (visible waypoint2 waypoint5)
       (visible waypoint5 waypoint4)
       (visible waypoint4 waypoint5)
       (at_soil_sample waypoint1)
       (at_rock_sample waypoint2)
       (at_soil_sample waypoint3)
       (at_rock_sample waypoint3)
       (at_soil_sample waypoint4)
       (at_rock_sample waypoint4)
       (at_rock_sample waypoint5)
       (at_lander general waypoint0)
       (channel_free general)
       (at rover0 waypoint2)
       (available rover0)
       (store_of rover0store rover0)
       (empty rover0store)
       (equipped_for_soil_analysis rover0)
       (equipped_for_rock_analysis rover0)
       (can_traverse rover0 waypoint2 waypoint0)
       (can_traverse rover0 waypoint0 waypoint2)
       (can_traverse rover0 waypoint2 waypoint3)
       (can_traverse rover0 waypoint3 waypoint2)
       (can_traverse rover0 waypoint2 waypoint4)
       (can_traverse rover0 waypoint4 waypoint2)
       (can_traverse rover0 waypoint0 waypoint1)
       (can_traverse rover0 waypoint1 waypoint0)
       (can_traverse rover0 waypoint3 waypoint5)
       (can_traverse rover0 waypoint5 waypoint3)
       (visible_from objective0 waypoint0)
       (visible_from objective0 waypoint1)
       (visible_from objective0 waypoint2)
       (visible_from objective1 waypoint0)
       (visible_from objective2 waypoint0)
       (visible_from objective2 waypoint1)
       (visible_from objective2 waypoint2))
  (:goal (and 
       (communicated_rock_data waypoint4)
       (communicated_rock_data waypoint5)
       (communicated_soil_data waypoint4)
       (communicated_soil_data waypoint3)
       (communicated_soil_data waypoint1))))