(define (problem ipc3-pfile04) (:domain rover)
  (:objects objective0 objective1 objective2 - objective
             camera0 - camera
             waypoint0 waypoint1 waypoint2 waypoint3 - waypoint
             rover1store - store
             rover1 - rover
             colour high_res low_res - mode
             general - lander
            )
  (:init
       (visible waypoint1 waypoint0)
       (visible waypoint0 waypoint1)
       (visible waypoint2 waypoint1)
       (visible waypoint1 waypoint2)
       (visible waypoint2 waypoint3)
       (visible waypoint3 waypoint2)
       (visible waypoint3 waypoint1)
       (visible waypoint1 waypoint3)
       (at_rock_sample waypoint1)
       (at_soil_sample waypoint2)
       (at_soil_sample waypoint3)
       (at_rock_sample waypoint3)
       (at_lander general waypoint2)
       (channel_free general)
       (at rover1 waypoint2)
       (available rover1)
       (store_of rover1store rover1)
       (empty rover1store)
       (equipped_for_soil_analysis rover1)
       (equipped_for_rock_analysis rover1)
       (equipped_for_imaging rover1)
       (can_traverse rover1 waypoint2 waypoint1)
       (can_traverse rover1 waypoint1 waypoint2)
       (can_traverse rover1 waypoint2 waypoint3)
       (can_traverse rover1 waypoint3 waypoint2)
       (can_traverse rover1 waypoint1 waypoint0)
       (can_traverse rover1 waypoint0 waypoint1)
       (on_board camera0 rover1)
       (calibration_target camera0 objective0)
       (supports camera0 colour)
       (supports camera0 high_res)
       (visible_from objective0 waypoint0)
       (visible_from objective0 waypoint1)
       (visible_from objective0 waypoint2)
       (visible_from objective0 waypoint3)
       (visible_from objective1 waypoint0)
       (visible_from objective1 waypoint1)
       (visible_from objective2 waypoint0)
       (visible_from objective2 waypoint1)
       (visible_from objective2 waypoint2))
  (:goal (and 
       (communicated_image_data objective0 high_res)
       (communicated_rock_data waypoint1)
       (communicated_soil_data waypoint3))))