(define (problem rover1-ipc3-pfile10-aux) (:domain rover)
  (:objects colour high_res low_res - mode
             rover1 - rover
             rover1store - store
             waypoint2 - waypoint
             camera0 camera1 camera2 camera3 - camera
             objective0 objective1 objective2 objective3 - objective
            )
  (:init
       (visible_from objective3 waypoint5)
       (visible_from objective3 waypoint4)
       (visible_from objective3 waypoint3)
       (visible_from objective3 waypoint2)
       (visible_from objective3 waypoint1)
       (visible_from objective3 waypoint0)
       (visible_from objective2 waypoint3)
       (visible_from objective2 waypoint2)
       (visible_from objective2 waypoint1)
       (visible_from objective2 waypoint0)
       (visible_from objective1 waypoint3)
       (visible_from objective1 waypoint2)
       (visible_from objective1 waypoint1)
       (visible_from objective1 waypoint0)
       (visible_from objective0 waypoint0)
       (supports camera3 low_res)
       (supports camera3 high_res)
       (calibration_target camera3 objective2)
       (on_board camera3 rover1)
       (supports camera2 low_res)
       (supports camera2 colour)
       (calibration_target camera2 objective1)
       (on_board camera2 rover1)
       (supports camera1 colour)
       (calibration_target camera1 objective3)
       (on_board camera1 rover1)
       (supports camera0 low_res)
       (calibration_target camera0 objective2)
       (on_board camera0 rover1)
       (can_traverse rover1 waypoint6 waypoint0)
       (can_traverse rover1 waypoint0 waypoint6)
       (can_traverse rover1 waypoint2 waypoint0)
       (can_traverse rover1 waypoint0 waypoint2)
       (can_traverse rover1 waypoint1 waypoint0)
       (can_traverse rover1 waypoint0 waypoint1)
       (equipped_for_imaging rover1)
       (equipped_for_soil_analysis rover1)
       (empty rover1store)
       (store_of rover1store rover1)
       (available rover1)
       (at rover1 waypoint0)
       (channel_free general)
       (at_lander general waypoint1)
       (at_rock_sample waypoint6)
       (at_soil_sample waypoint6)
       (at_rock_sample waypoint4)
       (at_soil_sample waypoint4)
       (at_rock_sample waypoint3)
       (at_soil_sample waypoint3)
       (at_rock_sample waypoint1)
       (at_rock_sample waypoint0)
       (at_soil_sample waypoint0)
       (visible waypoint4 waypoint6)
       (visible waypoint6 waypoint4)
       (visible waypoint6 waypoint5)
       (visible waypoint5 waypoint6)
       (visible waypoint0 waypoint5)
       (visible waypoint5 waypoint0)
       (visible waypoint3 waypoint4)
       (visible waypoint4 waypoint3)
       (visible waypoint1 waypoint4)
       (visible waypoint4 waypoint1)
       (visible waypoint0 waypoint4)
       (visible waypoint4 waypoint0)
       (visible waypoint5 waypoint3)
       (visible waypoint3 waypoint5)
       (visible waypoint6 waypoint2)
       (visible waypoint2 waypoint6)
       (visible waypoint4 waypoint2)
       (visible waypoint2 waypoint4)
       (visible waypoint0 waypoint2)
       (visible waypoint2 waypoint0)
       (visible waypoint5 waypoint1)
       (visible waypoint1 waypoint5)
       (visible waypoint2 waypoint1)
       (visible waypoint1 waypoint2)
       (visible waypoint0 waypoint1)
       (visible waypoint1 waypoint0)
       (visible waypoint6 waypoint0)
       (visible waypoint0 waypoint6)
       (anon-rover0-2 rover0 waypoint1 waypoint5)
       (anon-rover0-2 rover0 waypoint6 waypoint4)
       (anon-rover0-2 rover0 waypoint4 waypoint6)
       (anon-rover0-2 rover0 waypoint3 waypoint4)
       (anon-rover0-2 rover0 waypoint4 waypoint3)
       (anon-rover0-2 rover0 waypoint4 waypoint1)
       (anon-rover0-2 rover0 waypoint0 waypoint4)
       (anon-rover0-2 rover0 waypoint4 waypoint0)
       (anon-rover0-4 rover0)
       (anon-rover0-3 rover0)
       (anon-rover0-6 anon-rover0-18)
       (anon-rover0-14 anon-rover0-18 rover0)
       (anon-rover0-12 rover0)
       (anon-rover0-1 rover0 waypoint4))
  (:goal (and 
       (communicated_rock_data waypoint1)
       (communicated_rock_data waypoint0)
       (communicated_rock_data waypoint3)
       (communicated_rock_data waypoint4)
       (communicated_soil_data waypoint4)
       (communicated_soil_data waypoint3)
       (communicated_soil_data waypoint6)
       (communicated_image_data objective3 low_res)
       (communicated_image_data objective2 colour)
       (communicated_image_data objective3 colour)
       (communicated_soil_data waypoint0))))