(define (problem ipc3-pfile09) (:domain rover)
  (:objects objective0 objective1 objective2 - objective
             camera1 camera2 - camera
             waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 - waypoint
             rover0store - store
             rover0 - rover
             colour high_res low_res - mode
             general - lander
            )
  (:init
       (visible waypoint0 waypoint5)
       (visible waypoint5 waypoint0)
       (visible waypoint0 waypoint6)
       (visible waypoint6 waypoint0)
       (visible waypoint1 waypoint0)
       (visible waypoint0 waypoint1)
       (visible waypoint1 waypoint2)
       (visible waypoint2 waypoint1)
       (visible waypoint1 waypoint4)
       (visible waypoint4 waypoint1)
       (visible waypoint1 waypoint6)
       (visible waypoint6 waypoint1)
       (visible waypoint2 waypoint0)
       (visible waypoint0 waypoint2)
       (visible waypoint2 waypoint5)
       (visible waypoint5 waypoint2)
       (visible waypoint2 waypoint6)
       (visible waypoint6 waypoint2)
       (visible waypoint3 waypoint0)
       (visible waypoint0 waypoint3)
       (visible waypoint3 waypoint1)
       (visible waypoint1 waypoint3)
       (visible waypoint4 waypoint3)
       (visible waypoint3 waypoint4)
       (visible waypoint4 waypoint6)
       (visible waypoint6 waypoint4)
       (visible waypoint5 waypoint1)
       (visible waypoint1 waypoint5)
       (visible waypoint6 waypoint3)
       (visible waypoint3 waypoint6)
       (visible waypoint6 waypoint5)
       (visible waypoint5 waypoint6)
       (at_soil_sample waypoint0)
       (at_rock_sample waypoint0)
       (at_soil_sample waypoint1)
       (at_rock_sample waypoint1)
       (at_rock_sample waypoint3)
       (at_soil_sample waypoint4)
       (at_soil_sample waypoint5)
       (at_rock_sample waypoint5)
       (at_soil_sample waypoint6)
       (at_rock_sample waypoint6)
       (at_lander general waypoint4)
       (channel_free general)
       (at rover0 waypoint5)
       (available rover0)
       (store_of rover0store rover0)
       (empty rover0store)
       (equipped_for_imaging rover0)
       (can_traverse rover0 waypoint5 waypoint0)
       (can_traverse rover0 waypoint0 waypoint5)
       (can_traverse rover0 waypoint5 waypoint1)
       (can_traverse rover0 waypoint1 waypoint5)
       (can_traverse rover0 waypoint5 waypoint2)
       (can_traverse rover0 waypoint2 waypoint5)
       (can_traverse rover0 waypoint5 waypoint6)
       (can_traverse rover0 waypoint6 waypoint5)
       (can_traverse rover0 waypoint1 waypoint3)
       (can_traverse rover0 waypoint3 waypoint1)
       (can_traverse rover0 waypoint1 waypoint4)
       (can_traverse rover0 waypoint4 waypoint1)
       (on_board camera1 rover0)
       (calibration_target camera1 objective2)
       (supports camera1 colour)
       (on_board camera2 rover0)
       (calibration_target camera2 objective0)
       (supports camera2 low_res)
       (visible_from objective0 waypoint0)
       (visible_from objective0 waypoint1)
       (visible_from objective0 waypoint2)
       (visible_from objective1 waypoint0)
       (visible_from objective1 waypoint1)
       (visible_from objective1 waypoint2)
       (visible_from objective1 waypoint3)
       (visible_from objective1 waypoint4)
       (visible_from objective1 waypoint5)
       (visible_from objective2 waypoint0)
       (visible_from objective2 waypoint1)
       (visible_from objective2 waypoint2)
       (visible_from objective2 waypoint3)
       (visible_from objective2 waypoint4)
       (visible_from objective2 waypoint5)
       (visible_from objective2 waypoint6))
  (:goal (and 
       (communicated_image_data objective2 colour)
       (communicated_image_data objective2 low_res))))