(define (problem ipc3-pfile17) (:domain rover)
  (:objects objective0 objective1 objective2 objective3 objective4 objective5 - objective
             camera1 camera3 - camera
             waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 - waypoint
             rover3store - store
             rover3 - rover
             colour high_res low_res - mode
             general - lander
            )
  (:init
       (visible waypoint1 waypoint0)
       (visible waypoint0 waypoint1)
       (visible waypoint1 waypoint8)
       (visible waypoint8 waypoint1)
       (visible waypoint1 waypoint11)
       (visible waypoint11 waypoint1)
       (visible waypoint1 waypoint14)
       (visible waypoint14 waypoint1)
       (visible waypoint2 waypoint6)
       (visible waypoint6 waypoint2)
       (visible waypoint2 waypoint9)
       (visible waypoint9 waypoint2)
       (visible waypoint3 waypoint0)
       (visible waypoint0 waypoint3)
       (visible waypoint3 waypoint2)
       (visible waypoint2 waypoint3)
       (visible waypoint3 waypoint6)
       (visible waypoint6 waypoint3)
       (visible waypoint3 waypoint7)
       (visible waypoint7 waypoint3)
       (visible waypoint3 waypoint11)
       (visible waypoint11 waypoint3)
       (visible waypoint3 waypoint13)
       (visible waypoint13 waypoint3)
       (visible waypoint4 waypoint1)
       (visible waypoint1 waypoint4)
       (visible waypoint4 waypoint2)
       (visible waypoint2 waypoint4)
       (visible waypoint4 waypoint10)
       (visible waypoint10 waypoint4)
       (visible waypoint4 waypoint14)
       (visible waypoint14 waypoint4)
       (visible waypoint5 waypoint1)
       (visible waypoint1 waypoint5)
       (visible waypoint5 waypoint2)
       (visible waypoint2 waypoint5)
       (visible waypoint5 waypoint3)
       (visible waypoint3 waypoint5)
       (visible waypoint5 waypoint8)
       (visible waypoint8 waypoint5)
       (visible waypoint5 waypoint14)
       (visible waypoint14 waypoint5)
       (visible waypoint6 waypoint0)
       (visible waypoint0 waypoint6)
       (visible waypoint6 waypoint4)
       (visible waypoint4 waypoint6)
       (visible waypoint6 waypoint5)
       (visible waypoint5 waypoint6)
       (visible waypoint6 waypoint7)
       (visible waypoint7 waypoint6)
       (visible waypoint6 waypoint10)
       (visible waypoint10 waypoint6)
       (visible waypoint6 waypoint12)
       (visible waypoint12 waypoint6)
       (visible waypoint6 waypoint13)
       (visible waypoint13 waypoint6)
       (visible waypoint7 waypoint8)
       (visible waypoint8 waypoint7)
       (visible waypoint7 waypoint9)
       (visible waypoint9 waypoint7)
       (visible waypoint8 waypoint2)
       (visible waypoint2 waypoint8)
       (visible waypoint8 waypoint3)
       (visible waypoint3 waypoint8)
       (visible waypoint8 waypoint10)
       (visible waypoint10 waypoint8)
       (visible waypoint9 waypoint8)
       (visible waypoint8 waypoint9)
       (visible waypoint10 waypoint0)
       (visible waypoint0 waypoint10)
       (visible waypoint10 waypoint3)
       (visible waypoint3 waypoint10)
       (visible waypoint11 waypoint2)
       (visible waypoint2 waypoint11)
       (visible waypoint11 waypoint4)
       (visible waypoint4 waypoint11)
       (visible waypoint11 waypoint8)
       (visible waypoint8 waypoint11)
       (visible waypoint11 waypoint9)
       (visible waypoint9 waypoint11)
       (visible waypoint11 waypoint10)
       (visible waypoint10 waypoint11)
       (visible waypoint12 waypoint0)
       (visible waypoint0 waypoint12)
       (visible waypoint12 waypoint1)
       (visible waypoint1 waypoint12)
       (visible waypoint12 waypoint5)
       (visible waypoint5 waypoint12)
       (visible waypoint12 waypoint7)
       (visible waypoint7 waypoint12)
       (visible waypoint13 waypoint0)
       (visible waypoint0 waypoint13)
       (visible waypoint13 waypoint5)
       (visible waypoint5 waypoint13)
       (visible waypoint13 waypoint14)
       (visible waypoint14 waypoint13)
       (visible waypoint14 waypoint2)
       (visible waypoint2 waypoint14)
       (visible waypoint14 waypoint3)
       (visible waypoint3 waypoint14)
       (visible waypoint14 waypoint9)
       (visible waypoint9 waypoint14)
       (visible waypoint14 waypoint10)
       (visible waypoint10 waypoint14)
       (at_soil_sample waypoint0)
       (at_rock_sample waypoint1)
       (at_soil_sample waypoint2)
       (at_rock_sample waypoint2)
       (at_soil_sample waypoint3)
       (at_rock_sample waypoint3)
       (at_soil_sample waypoint4)
       (at_rock_sample waypoint4)
       (at_soil_sample waypoint5)
       (at_rock_sample waypoint5)
       (at_rock_sample waypoint6)
       (at_rock_sample waypoint7)
       (at_soil_sample waypoint9)
       (at_rock_sample waypoint9)
       (at_rock_sample waypoint10)
       (at_rock_sample waypoint11)
       (at_rock_sample waypoint12)
       (at_soil_sample waypoint13)
       (at_rock_sample waypoint13)
       (at_soil_sample waypoint14)
       (at_rock_sample waypoint14)
       (at_lander general waypoint13)
       (channel_free general)
       (at rover3 waypoint13)
       (available rover3)
       (store_of rover3store rover3)
       (empty rover3store)
       (equipped_for_soil_analysis rover3)
       (equipped_for_imaging rover3)
       (can_traverse rover3 waypoint13 waypoint0)
       (can_traverse rover3 waypoint0 waypoint13)
       (can_traverse rover3 waypoint13 waypoint3)
       (can_traverse rover3 waypoint3 waypoint13)
       (can_traverse rover3 waypoint13 waypoint5)
       (can_traverse rover3 waypoint5 waypoint13)
       (can_traverse rover3 waypoint13 waypoint6)
       (can_traverse rover3 waypoint6 waypoint13)
       (can_traverse rover3 waypoint0 waypoint1)
       (can_traverse rover3 waypoint1 waypoint0)
       (can_traverse rover3 waypoint0 waypoint10)
       (can_traverse rover3 waypoint10 waypoint0)
       (can_traverse rover3 waypoint3 waypoint7)
       (can_traverse rover3 waypoint7 waypoint3)
       (can_traverse rover3 waypoint3 waypoint8)
       (can_traverse rover3 waypoint8 waypoint3)
       (can_traverse rover3 waypoint3 waypoint11)
       (can_traverse rover3 waypoint11 waypoint3)
       (can_traverse rover3 waypoint5 waypoint2)
       (can_traverse rover3 waypoint2 waypoint5)
       (can_traverse rover3 waypoint5 waypoint12)
       (can_traverse rover3 waypoint12 waypoint5)
       (can_traverse rover3 waypoint5 waypoint14)
       (can_traverse rover3 waypoint14 waypoint5)
       (can_traverse rover3 waypoint1 waypoint4)
       (can_traverse rover3 waypoint4 waypoint1)
       (on_board camera1 rover3)
       (calibration_target camera1 objective2)
       (supports camera1 colour)
       (on_board camera3 rover3)
       (calibration_target camera3 objective5)
       (supports camera3 colour)
       (visible_from objective0 waypoint0)
       (visible_from objective0 waypoint1)
       (visible_from objective0 waypoint2)
       (visible_from objective0 waypoint3)
       (visible_from objective1 waypoint0)
       (visible_from objective1 waypoint1)
       (visible_from objective2 waypoint0)
       (visible_from objective2 waypoint1)
       (visible_from objective2 waypoint2)
       (visible_from objective2 waypoint3)
       (visible_from objective2 waypoint4)
       (visible_from objective2 waypoint5)
       (visible_from objective2 waypoint6)
       (visible_from objective2 waypoint7)
       (visible_from objective2 waypoint8)
       (visible_from objective2 waypoint9)
       (visible_from objective2 waypoint10)
       (visible_from objective2 waypoint11)
       (visible_from objective2 waypoint12)
       (visible_from objective2 waypoint13)
       (visible_from objective2 waypoint14)
       (visible_from objective3 waypoint0)
       (visible_from objective3 waypoint1)
       (visible_from objective3 waypoint2)
       (visible_from objective3 waypoint3)
       (visible_from objective3 waypoint4)
       (visible_from objective3 waypoint5)
       (visible_from objective4 waypoint0)
       (visible_from objective4 waypoint1)
       (visible_from objective4 waypoint2)
       (visible_from objective4 waypoint3)
       (visible_from objective4 waypoint4)
       (visible_from objective4 waypoint5)
       (visible_from objective4 waypoint6)
       (visible_from objective4 waypoint7)
       (visible_from objective4 waypoint8)
       (visible_from objective4 waypoint9)
       (visible_from objective4 waypoint10)
       (visible_from objective4 waypoint11)
       (visible_from objective4 waypoint12)
       (visible_from objective5 waypoint0)
       (visible_from objective5 waypoint1))
  (:goal (and 
       (communicated_image_data objective4 colour)
       (communicated_image_data objective5 colour)
       (communicated_image_data objective3 colour)
       (communicated_image_data objective2 colour)
       (communicated_soil_data waypoint3)
       (communicated_soil_data waypoint2)
       (communicated_soil_data waypoint5)
       (communicated_soil_data waypoint14))))