(define (problem pfile14-ma) (:domain zenotravel)
  (:objects fl6 fl5 fl4 fl3 fl2 fl1 fl0 - flevel
             city9 city8 city7 city6 city5 city4 city3 city2 city1 city0 - city
             person10 person9 person8 person7 person6 person5 person4 person3 person2 person1 - person
             plane4 - aircraft
            )
  (:init
       (at-airplane plane4 city8)
       (fuel-level plane4 fl3)
       (at person1 city9)
       (at person2 city1)
       (at person3 city0)
       (at person4 city9)
       (at person5 city6)
       (at person6 city0)
       (at person7 city7)
       (at person8 city6)
       (at person9 city4)
       (at person10 city7)
       (next fl0 fl1)
       (next fl1 fl2)
       (next fl2 fl3)
       (next fl3 fl4)
       (next fl4 fl5)
       (next fl5 fl6))
  (:goal (and 
       (at person10 city9)
       (at person9 city5)
       (at person8 city1)
       (at person7 city5)
       (at person6 city6)
       (at person5 city1)
       (at person4 city7)
       (at person3 city2)
       (at person2 city8)
       (at-airplane plane4 city5))))