(define (problem pfile15-ma) (:domain zenotravel)
  (:objects fl6 fl5 fl4 fl3 fl2 fl1 fl0 - flevel
             city11 city10 city9 city8 city7 city6 city5 city4 city3 city2 city1 city0 - city
             person15 person14 person13 person12 person11 person10 person9 person8 person7 person6 person5 person4 person3 person2 person1 - person
             plane1 - aircraft
            )
  (:init
       (at-airplane plane1 city0)
       (fuel-level plane1 fl0)
       (at person1 city8)
       (at person2 city10)
       (at person3 city7)
       (at person4 city5)
       (at person5 city1)
       (at person6 city10)
       (at person7 city11)
       (at person8 city8)
       (at person9 city9)
       (at person10 city11)
       (at person11 city4)
       (at person12 city5)
       (at person13 city8)
       (at person14 city4)
       (at person15 city1)
       (next fl0 fl1)
       (next fl1 fl2)
       (next fl2 fl3)
       (next fl3 fl4)
       (next fl4 fl5)
       (next fl5 fl6))
  (:goal (and 
       (at person15 city6)
       (at person14 city4)
       (at person13 city11)
       (at person12 city4)
       (at person11 city6)
       (at person10 city9)
       (at person8 city11)
       (at person7 city2)
       (at person6 city11)
       (at person5 city8)
       (at person4 city6)
       (at person3 city7)
       (at person2 city4)
       (at person1 city1))))