(define (problem pfile16) (:domain satellite)
  (:objects star24 phenomenon23 planet22 planet21 star20 planet19 phenomenon18 phenomenon17 star16 star15 star14 star13 star12 planet11 planet10 phenomenon9 planet8 planet7 planet6 phenomenon5 groundstation1 star2 groundstation4 star3 groundstation0 - direction
             spectrograph3 thermograph1 infrared4 image2 image0 - mode
             instrument16 instrument15 instrument14 - instrument
             satellite6 - satellite
            )
  (:init
       (supports instrument14 spectrograph3)
       (supports instrument14 thermograph1)
       (supports instrument14 image0)
       (calibration_target instrument14 star3)
       (supports instrument15 image0)
       (supports instrument15 thermograph1)
       (supports instrument15 image2)
       (calibration_target instrument15 groundstation4)
       (supports instrument16 spectrograph3)
       (supports instrument16 image2)
       (calibration_target instrument16 groundstation0)
       (on_board instrument14 satellite6)
       (on_board instrument15 satellite6)
       (on_board instrument16 satellite6)
       (power_avail satellite6)
       (pointing satellite6 planet11))
  (:goal (and 
       (have_image phenomenon23 image0)
       (have_image planet22 image2)
       (have_image planet21 thermograph1)
       (have_image star20 image0)
       (have_image phenomenon18 spectrograph3)
       (have_image star16 thermograph1)
       (have_image star15 image0)
       (have_image star14 thermograph1)
       (have_image star13 image0)
       (have_image star12 image0)
       (have_image planet10 image0)
       (have_image phenomenon9 image2)
       (have_image planet8 thermograph1)
       (have_image planet7 image0)
       (have_image phenomenon5 thermograph1))))