(define (problem pfile19) (:domain satellite)
  (:objects phenomenon24 star23 planet22 planet21 phenomenon20 star19 star18 planet17 star16 planet15 star14 phenomenon13 star12 phenomenon11 star10 planet9 phenomenon8 phenomenon7 star6 phenomenon5 groundstation0 star3 star2 groundstation4 star1 - direction
             infrared3 spectrograph0 infrared7 thermograph1 image5 infrared2 spectrograph6 image4 - mode
             instrument7 instrument6 instrument5 instrument4 instrument3 - instrument
             satellite1 - satellite
            )
  (:init
       (supports instrument3 thermograph1)
       (supports instrument3 image5)
       (calibration_target instrument3 star1)
       (supports instrument4 spectrograph0)
       (calibration_target instrument4 star3)
       (supports instrument5 thermograph1)
       (supports instrument5 spectrograph0)
       (supports instrument5 spectrograph6)
       (calibration_target instrument5 groundstation4)
       (supports instrument6 image5)
       (supports instrument6 infrared7)
       (calibration_target instrument6 star3)
       (supports instrument7 spectrograph6)
       (supports instrument7 thermograph1)
       (supports instrument7 spectrograph0)
       (calibration_target instrument7 star2)
       (on_board instrument3 satellite1)
       (on_board instrument4 satellite1)
       (on_board instrument5 satellite1)
       (on_board instrument6 satellite1)
       (on_board instrument7 satellite1)
       (power_avail satellite1)
       (pointing satellite1 planet21))
  (:goal (and 
       (have_image phenomenon24 image5)
       (have_image phenomenon24 spectrograph6)
       (have_image planet21 image5)
       (have_image phenomenon20 spectrograph0)
       (have_image star19 thermograph1)
       (have_image planet17 image5)
       (have_image phenomenon13 infrared7)
       (have_image star12 thermograph1)
       (have_image star12 spectrograph6)
       (have_image star10 spectrograph6)
       (have_image planet9 spectrograph6)
       (have_image planet9 spectrograph0)
       (have_image phenomenon7 thermograph1)
       (have_image phenomenon5 infrared7))))