(define (problem pfile19) (:domain satellite)
  (:objects phenomenon24 star23 planet22 planet21 phenomenon20 star19 star18 planet17 star16 planet15 star14 phenomenon13 star12 phenomenon11 star10 planet9 phenomenon8 phenomenon7 star6 phenomenon5 groundstation0 star3 star2 groundstation4 star1 - direction
             infrared3 spectrograph0 infrared7 thermograph1 image5 infrared2 spectrograph6 image4 - mode
             instrument13 instrument12 instrument11 instrument10 instrument9 instrument8 - instrument
             satellite2 - satellite
            )
  (:init
       (supports instrument8 infrared3)
       (supports instrument8 infrared7)
       (calibration_target instrument8 star1)
       (supports instrument9 spectrograph0)
       (calibration_target instrument9 star3)
       (supports instrument10 image4)
       (supports instrument10 infrared7)
       (supports instrument10 image5)
       (calibration_target instrument10 groundstation4)
       (supports instrument11 infrared2)
       (calibration_target instrument11 star2)
       (supports instrument12 thermograph1)
       (calibration_target instrument12 star3)
       (supports instrument13 infrared3)
       (calibration_target instrument13 star2)
       (on_board instrument8 satellite2)
       (on_board instrument9 satellite2)
       (on_board instrument10 satellite2)
       (on_board instrument11 satellite2)
       (on_board instrument12 satellite2)
       (on_board instrument13 satellite2)
       (power_avail satellite2)
       (pointing satellite2 phenomenon5))
  (:goal (and 
       (have_image phenomenon24 image5)
       (have_image star23 infrared2)
       (have_image planet22 infrared2)
       (have_image planet21 image5)
       (have_image planet21 infrared3)
       (have_image phenomenon20 spectrograph0)
       (have_image star19 thermograph1)
       (have_image star19 infrared3)
       (have_image star18 infrared2)
       (have_image planet17 image4)
       (have_image planet17 image5)
       (have_image star16 image4)
       (have_image planet15 infrared2)
       (have_image star14 infrared2)
       (have_image phenomenon13 infrared2)
       (have_image phenomenon13 infrared7)
       (have_image star12 thermograph1)
       (have_image phenomenon11 infrared2)
       (have_image star10 infrared3)
       (have_image planet9 spectrograph0)
       (have_image phenomenon7 thermograph1)
       (have_image phenomenon5 image4)
       (have_image phenomenon5 infrared7))))