(define (problem pfile19) (:domain satellite)
  (:objects phenomenon24 star23 planet22 planet21 phenomenon20 star19 star18 planet17 star16 planet15 star14 phenomenon13 star12 phenomenon11 star10 planet9 phenomenon8 phenomenon7 star6 phenomenon5 groundstation0 star3 star2 groundstation4 star1 - direction
             infrared3 spectrograph0 infrared7 thermograph1 image5 infrared2 spectrograph6 image4 - mode
             instrument2 instrument1 instrument0 - instrument
             satellite0 - satellite
            )
  (:init
       (supports instrument0 infrared2)
       (supports instrument0 image4)
       (calibration_target instrument0 groundstation0)
       (supports instrument1 spectrograph0)
       (calibration_target instrument1 star3)
       (supports instrument2 infrared3)
       (supports instrument2 thermograph1)
       (supports instrument2 spectrograph0)
       (calibration_target instrument2 star1)
       (on_board instrument0 satellite0)
       (on_board instrument1 satellite0)
       (on_board instrument2 satellite0)
       (power_avail satellite0)
       (pointing satellite0 planet21))
  (:goal (and 
       (have_image star23 infrared2)
       (have_image planet22 infrared2)
       (have_image planet21 infrared3)
       (have_image phenomenon20 spectrograph0)
       (have_image star19 thermograph1)
       (have_image star19 infrared3)
       (have_image star18 infrared2)
       (have_image planet17 image4)
       (have_image star16 image4)
       (have_image planet15 infrared2)
       (have_image star14 infrared2)
       (have_image phenomenon13 infrared2)
       (have_image star12 thermograph1)
       (have_image phenomenon11 infrared2)
       (have_image star10 infrared3)
       (have_image planet9 spectrograph0)
       (have_image phenomenon7 thermograph1)
       (have_image phenomenon5 image4)
       (pointing satellite0 planet17))))