(define (problem pfile13) (:domain satellite)
  (:objects planet29 planet28 phenomenon27 star26 planet25 planet24 planet23 star22 star21 planet20 star19 phenomenon18 planet17 planet16 planet15 star14 planet13 phenomenon12 planet11 planet10 planet9 planet8 planet7 planet6 phenomenon5 groundstation3 star0 star4 star1 groundstation2 - direction
             image3 thermograph2 thermograph0 thermograph1 image4 - mode
             instrument8 instrument7 instrument6 - instrument
             satellite4 - satellite
            )
  (:init
       (supports instrument6 image3)
       (supports instrument6 thermograph1)
       (supports instrument6 thermograph0)
       (calibration_target instrument6 star4)
       (supports instrument7 thermograph2)
       (supports instrument7 thermograph0)
       (calibration_target instrument7 star0)
       (supports instrument8 image3)
       (supports instrument8 thermograph2)
       (calibration_target instrument8 groundstation3)
       (on_board instrument6 satellite4)
       (on_board instrument7 satellite4)
       (on_board instrument8 satellite4)
       (power_avail satellite4)
       (pointing satellite4 phenomenon5))
  (:goal (and 
       (have_image planet29 thermograph0)
       (have_image planet28 thermograph2)
       (have_image phenomenon27 thermograph1)
       (have_image star26 thermograph0)
       (have_image planet25 thermograph1)
       (have_image planet24 thermograph2)
       (have_image planet23 thermograph1)
       (have_image star21 thermograph1)
       (have_image star19 thermograph0)
       (have_image phenomenon18 image3)
       (have_image planet16 image3)
       (have_image planet15 thermograph0)
       (have_image star14 image3)
       (have_image planet13 thermograph1)
       (have_image phenomenon12 image3)
       (have_image planet11 thermograph2)
       (have_image planet10 thermograph1)
       (have_image planet9 thermograph0)
       (have_image planet8 image3)
       (have_image planet7 image3)
       (have_image phenomenon5 thermograph1)
       (pointing satellite4 planet11))))