(define (problem pfile-02-5) (:domain port)
  (:objects hoist1 - hoist
             level3 level2 level1 level0 - level
             crate4 crate3 crate2 crate1 crate0 - crate
             pallet3 pallet2 pallet1 pallet0 - pallet-dock
             pallet11 pallet10 pallet9 pallet8 pallet7 pallet6 pallet5 pallet4 - pallet-ship
             dock0 - dock
             ship1 ship0 - ship
            )
  (:init
       (clear pallet4)
       (clear pallet5)
       (clear pallet6)
       (clear pallet7)
       (clear pallet8)
       (clear pallet9)
       (clear pallet10)
       (clear pallet11)
       (clear crate3)
       (clear pallet1)
       (clear crate4)
       (clear crate0)
       (height crate4 level1)
       (on-dock crate4 pallet2)
       (at crate4 dock0)
       (height crate3 level3)
       (on-dock crate3 crate2)
       (at crate3 dock0)
       (height crate2 level2)
       (on-dock crate2 crate1)
       (at crate2 dock0)
       (height crate1 level1)
       (on-dock crate1 pallet0)
       (at crate1 dock0)
       (height crate0 level1)
       (on-dock crate0 pallet3)
       (at crate0 dock0)
       (height pallet11 level0)
       (at pallet11 ship1)
       (height pallet10 level0)
       (at pallet10 ship1)
       (height pallet9 level0)
       (at pallet9 ship1)
       (height pallet8 level0)
       (at pallet8 ship1)
       (available hoist1)
       (assigned hoist1 ship1)
       (height pallet7 level0)
       (at pallet7 ship0)
       (height pallet6 level0)
       (at pallet6 ship0)
       (height pallet5 level0)
       (at pallet5 ship0)
       (height pallet4 level0)
       (at pallet4 ship0)
       (height pallet3 level0)
       (at pallet3 dock0)
       (height pallet2 level0)
       (at pallet2 dock0)
       (height pallet1 level0)
       (at pallet1 dock0)
       (height pallet0 level0)
       (at pallet0 dock0)
       (next level2 level3)
       (next level1 level2)
       (next level0 level1))
  (:goal (and 
       (on-ship crate4 pallet11 ship1))))