(define (problem pfile-02-20) (:domain port)
  (:objects hoist1 - hoist
             level3 level2 level1 level0 - level
             crate19 crate18 crate17 crate16 crate15 crate14 crate13 crate12 crate11 crate10 crate9 crate8 crate7 crate6 crate5 crate4 crate3 crate2 crate1 crate0 - crate
             pallet9 pallet8 pallet7 pallet6 pallet5 pallet4 pallet3 pallet2 pallet1 pallet0 - pallet-dock
             pallet17 pallet16 pallet15 pallet14 pallet13 pallet12 pallet11 pallet10 - pallet-ship
             dock0 - dock
             ship1 ship0 - ship
            )
  (:init
       (clear pallet10)
       (clear pallet11)
       (clear pallet12)
       (clear pallet13)
       (clear pallet14)
       (clear pallet15)
       (clear pallet16)
       (clear pallet17)
       (clear crate13)
       (clear crate8)
       (clear crate19)
       (clear pallet3)
       (clear crate17)
       (clear crate5)
       (clear crate11)
       (clear crate18)
       (clear crate12)
       (clear crate14)
       (height crate19 level2)
       (on-dock crate19 crate1)
       (at crate19 dock0)
       (height crate18 level3)
       (on-dock crate18 crate15)
       (at crate18 dock0)
       (height crate17 level3)
       (on-dock crate17 crate16)
       (at crate17 dock0)
       (height crate16 level2)
       (on-dock crate16 crate7)
       (at crate16 dock0)
       (height crate15 level2)
       (on-dock crate15 crate10)
       (at crate15 dock0)
       (height crate14 level1)
       (on-dock crate14 pallet9)
       (at crate14 dock0)
       (height crate13 level1)
       (on-dock crate13 pallet0)
       (at crate13 dock0)
       (height crate12 level2)
       (on-dock crate12 crate3)
       (at crate12 dock0)
       (height crate11 level3)
       (on-dock crate11 crate9)
       (at crate11 dock0)
       (height crate10 level1)
       (on-dock crate10 pallet7)
       (at crate10 dock0)
       (height crate9 level2)
       (on-dock crate9 crate6)
       (at crate9 dock0)
       (height crate8 level2)
       (on-dock crate8 crate0)
       (at crate8 dock0)
       (height crate7 level1)
       (on-dock crate7 pallet4)
       (at crate7 dock0)
       (height crate6 level1)
       (on-dock crate6 pallet6)
       (at crate6 dock0)
       (height crate5 level3)
       (on-dock crate5 crate4)
       (at crate5 dock0)
       (height crate4 level2)
       (on-dock crate4 crate2)
       (at crate4 dock0)
       (height crate3 level1)
       (on-dock crate3 pallet8)
       (at crate3 dock0)
       (height crate2 level1)
       (on-dock crate2 pallet5)
       (at crate2 dock0)
       (height crate1 level1)
       (on-dock crate1 pallet2)
       (at crate1 dock0)
       (height crate0 level1)
       (on-dock crate0 pallet1)
       (at crate0 dock0)
       (height pallet17 level0)
       (at pallet17 ship1)
       (height pallet16 level0)
       (at pallet16 ship1)
       (height pallet15 level0)
       (at pallet15 ship1)
       (height pallet14 level0)
       (at pallet14 ship1)
       (available hoist1)
       (assigned hoist1 ship1)
       (height pallet13 level0)
       (at pallet13 ship0)
       (height pallet12 level0)
       (at pallet12 ship0)
       (height pallet11 level0)
       (at pallet11 ship0)
       (height pallet10 level0)
       (at pallet10 ship0)
       (height pallet9 level0)
       (at pallet9 dock0)
       (height pallet8 level0)
       (at pallet8 dock0)
       (height pallet7 level0)
       (at pallet7 dock0)
       (height pallet6 level0)
       (at pallet6 dock0)
       (height pallet5 level0)
       (at pallet5 dock0)
       (height pallet4 level0)
       (at pallet4 dock0)
       (height pallet3 level0)
       (at pallet3 dock0)
       (height pallet2 level0)
       (at pallet2 dock0)
       (height pallet1 level0)
       (at pallet1 dock0)
       (height pallet0 level0)
       (at pallet0 dock0)
       (next level2 level3)
       (next level1 level2)
       (next level0 level1))
  (:goal (and 
       (on-ship crate0 pallet15 ship1)
       (on-ship crate6 pallet17 ship1)
       (on-ship crate9 crate0 ship1)
       (on-ship crate11 crate9 ship1)
       (on-ship crate14 pallet14 ship1)
       (on-ship crate15 crate6 ship1)
       (on-ship crate16 crate14 ship1)
       (on-ship crate18 crate16 ship1)
       (on-ship crate19 pallet16 ship1))))