(define (problem pfile15) (:domain satellite)
  (:objects planet24 planet23 planet22 planet21 planet20 star19 star18 planet17 phenomenon16 star15 planet14 star13 star12 planet11 phenomenon10 phenomenon9 star8 planet7 planet6 phenomenon5 star4 star1 groundstation2 groundstation0 star3 - direction
             thermograph4 spectrograph2 thermograph3 infrared0 image1 - mode
             instrument5 instrument4 - instrument
             satellite2 - satellite
            )
  (:init
       (supports instrument4 thermograph3)
       (supports instrument4 thermograph4)
       (supports instrument4 spectrograph2)
       (calibration_target instrument4 star1)
       (supports instrument5 thermograph3)
       (supports instrument5 image1)
       (supports instrument5 infrared0)
       (calibration_target instrument5 groundstation2)
       (on_board instrument4 satellite2)
       (on_board instrument5 satellite2)
       (power_avail satellite2)
       (pointing satellite2 star19))
  (:goal (and 
       (have_image planet24 infrared0)
       (have_image planet23 thermograph3)
       (have_image planet22 image1)
       (have_image planet21 infrared0)
       (have_image planet20 image1)
       (have_image star18 image1)
       (have_image planet17 thermograph3)
       (have_image phenomenon16 image1)
       (have_image star15 thermograph4)
       (have_image planet14 thermograph4)
       (have_image star13 thermograph3)
       (have_image star12 thermograph3)
       (have_image planet11 image1)
       (have_image phenomenon10 image1)
       (have_image phenomenon9 infrared0)
       (have_image planet7 infrared0)
       (have_image planet6 spectrograph2)
       (have_image phenomenon5 spectrograph2)
       (pointing satellite2 star13))))