(define (problem pfile20) (:domain satellite)
  (:objects star24 star23 planet22 phenomenon21 star20 phenomenon19 planet18 planet17 star16 planet15 phenomenon14 planet13 phenomenon12 star11 star10 planet9 phenomenon8 planet7 star6 phenomenon5 groundstation1 groundstation3 star4 star2 star0 - direction
             spectrograph0 image4 thermograph7 image2 infrared9 image3 infrared5 thermograph8 infrared1 spectrograph6 - mode
             instrument15 instrument14 instrument13 instrument12 instrument11 instrument10 - instrument
             satellite1 - satellite
            )
  (:init
       (supports instrument10 infrared1)
       (supports instrument10 thermograph8)
       (supports instrument10 spectrograph6)
       (calibration_target instrument10 star4)
       (supports instrument11 image4)
       (supports instrument11 thermograph7)
       (supports instrument11 infrared1)
       (calibration_target instrument11 groundstation3)
       (supports instrument12 infrared9)
       (supports instrument12 thermograph8)
       (supports instrument12 infrared5)
       (calibration_target instrument12 groundstation3)
       (supports instrument13 image2)
       (supports instrument13 infrared1)
       (calibration_target instrument13 star4)
       (supports instrument14 image3)
       (calibration_target instrument14 groundstation3)
       (supports instrument15 thermograph7)
       (calibration_target instrument15 star2)
       (on_board instrument10 satellite1)
       (on_board instrument11 satellite1)
       (on_board instrument12 satellite1)
       (on_board instrument13 satellite1)
       (on_board instrument14 satellite1)
       (on_board instrument15 satellite1)
       (power_avail satellite1)
       (pointing satellite1 phenomenon19))
  (:goal (and 
       (have_image star24 infrared5)
       (have_image star24 spectrograph6)
       (have_image star23 infrared9)
       (have_image star23 image2)
       (have_image planet22 spectrograph6)
       (have_image planet22 image2)
       (have_image phenomenon21 thermograph7)
       (have_image phenomenon21 image2)
       (have_image phenomenon21 image4)
       (have_image phenomenon19 image4)
       (have_image phenomenon19 image2)
       (have_image planet18 thermograph7)
       (have_image planet18 infrared5)
       (have_image planet18 infrared9)
       (have_image star16 image4)
       (have_image star16 image3)
       (have_image planet15 image3)
       (have_image phenomenon14 thermograph7)
       (have_image planet13 image2)
       (have_image planet13 spectrograph6)
       (have_image planet13 infrared5)
       (have_image phenomenon12 image4)
       (have_image star11 image3)
       (have_image star11 image4)
       (have_image star11 thermograph7)
       (have_image star10 spectrograph6)
       (have_image planet9 spectrograph6)
       (have_image phenomenon8 thermograph7)
       (have_image phenomenon8 infrared5)
       (have_image phenomenon8 spectrograph6)
       (have_image planet7 image2)
       (have_image planet7 infrared5)
       (have_image planet7 spectrograph6)
       (have_image star6 image3)
       (have_image star6 spectrograph6)
       (have_image phenomenon5 image3)
       (have_image phenomenon5 thermograph8)
       (pointing satellite1 phenomenon19))))