(define (problem pfile19) (:domain satellite)
  (:objects phenomenon24 star23 planet22 planet21 phenomenon20 star19 star18 planet17 star16 planet15 star14 phenomenon13 star12 phenomenon11 star10 planet9 phenomenon8 phenomenon7 star6 phenomenon5 groundstation0 star3 star2 groundstation4 star1 - direction
             infrared3 spectrograph0 infrared7 thermograph1 image5 infrared2 spectrograph6 image4 - mode
             instrument21 instrument20 instrument19 instrument18 instrument17 instrument16 instrument15 instrument14 - instrument
             satellite3 - satellite
            )
  (:init
       (supports instrument14 thermograph1)
       (supports instrument14 infrared2)
       (calibration_target instrument14 groundstation4)
       (supports instrument15 infrared2)
       (calibration_target instrument15 star1)
       (supports instrument16 image4)
       (supports instrument16 spectrograph6)
       (calibration_target instrument16 star2)
       (supports instrument17 image4)
       (supports instrument17 infrared7)
       (supports instrument17 image5)
       (calibration_target instrument17 groundstation0)
       (supports instrument18 image4)
       (supports instrument18 spectrograph6)
       (calibration_target instrument18 star2)
       (supports instrument19 infrared3)
       (supports instrument19 infrared7)
       (supports instrument19 spectrograph6)
       (calibration_target instrument19 star3)
       (supports instrument20 infrared3)
       (supports instrument20 infrared2)
       (calibration_target instrument20 star2)
       (supports instrument21 infrared2)
       (supports instrument21 thermograph1)
       (calibration_target instrument21 groundstation4)
       (on_board instrument14 satellite3)
       (on_board instrument15 satellite3)
       (on_board instrument16 satellite3)
       (on_board instrument17 satellite3)
       (on_board instrument18 satellite3)
       (on_board instrument19 satellite3)
       (on_board instrument20 satellite3)
       (on_board instrument21 satellite3)
       (power_avail satellite3)
       (pointing satellite3 phenomenon20))
  (:goal (and 
       (have_image phenomenon24 image5)
       (have_image phenomenon24 spectrograph6)
       (have_image star23 infrared2)
       (have_image planet22 infrared2)
       (have_image planet21 image5)
       (have_image planet21 infrared3)
       (have_image star19 thermograph1)
       (have_image star19 infrared3)
       (have_image star18 infrared2)
       (have_image planet17 image4)
       (have_image planet17 image5)
       (have_image star16 image4)
       (have_image planet15 infrared2)
       (have_image star14 infrared2)
       (have_image phenomenon13 infrared2)
       (have_image phenomenon13 infrared7)
       (have_image star12 thermograph1)
       (have_image star12 spectrograph6)
       (have_image phenomenon11 infrared2)
       (have_image star10 spectrograph6)
       (have_image star10 infrared3)
       (have_image planet9 spectrograph6)
       (have_image phenomenon7 thermograph1)
       (have_image phenomenon5 image4)
       (have_image phenomenon5 infrared7))))