(define (problem pfile17) (:domain satellite)
  (:objects phenomenon24 phenomenon23 star22 star21 phenomenon20 phenomenon19 star18 phenomenon17 planet16 phenomenon15 phenomenon14 planet13 planet12 planet11 star10 phenomenon9 star8 planet7 planet6 planet5 star3 groundstation0 star1 groundstation4 groundstation2 - direction
             infrared2 image4 thermograph1 image0 infrared3 - mode
             instrument8 instrument7 instrument6 - instrument
             satellite3 - satellite
            )
  (:init
       (supports instrument6 image0)
       (supports instrument6 infrared2)
       (calibration_target instrument6 groundstation2)
       (supports instrument7 image0)
       (supports instrument7 infrared3)
       (calibration_target instrument7 groundstation0)
       (supports instrument8 infrared2)
       (supports instrument8 image4)
       (supports instrument8 image0)
       (calibration_target instrument8 groundstation4)
       (on_board instrument6 satellite3)
       (on_board instrument7 satellite3)
       (on_board instrument8 satellite3)
       (power_avail satellite3)
       (pointing satellite3 star21))
  (:goal (and 
       (have_image phenomenon24 infrared3)
       (have_image phenomenon23 infrared3)
       (have_image star22 image4)
       (have_image star18 image4)
       (have_image planet16 infrared2)
       (have_image phenomenon15 infrared2)
       (have_image phenomenon14 infrared2)
       (have_image planet13 infrared3)
       (have_image planet11 image4)
       (have_image phenomenon9 image4)
       (have_image planet7 image4)
       (have_image planet6 image4)
       (have_image planet5 image0))))