(define (problem pfile12) (:domain satellite)
  (:objects phenomenon24 star23 star22 phenomenon21 planet20 star19 star18 phenomenon17 planet16 star15 star14 phenomenon13 star12 planet11 planet10 star9 planet8 star7 phenomenon6 planet5 star4 star2 groundstation1 star3 star0 - direction
             infrared3 spectrograph4 infrared1 infrared0 thermograph2 - mode
             instrument9 instrument8 instrument7 - instrument
             satellite4 - satellite
            )
  (:init
       (supports instrument7 infrared1)
       (supports instrument7 infrared3)
       (calibration_target instrument7 star2)
       (supports instrument8 infrared0)
       (supports instrument8 infrared3)
       (supports instrument8 spectrograph4)
       (calibration_target instrument8 star2)
       (supports instrument9 infrared3)
       (supports instrument9 spectrograph4)
       (supports instrument9 infrared1)
       (calibration_target instrument9 star4)
       (on_board instrument7 satellite4)
       (on_board instrument8 satellite4)
       (on_board instrument9 satellite4)
       (power_avail satellite4)
       (pointing satellite4 star14))
  (:goal (and 
       (have_image phenomenon24 infrared0)
       (have_image star23 spectrograph4)
       (have_image star22 infrared1)
       (have_image star18 spectrograph4)
       (have_image phenomenon17 spectrograph4)
       (have_image planet16 infrared1)
       (have_image star15 infrared3)
       (have_image phenomenon13 spectrograph4)
       (have_image planet11 infrared3)
       (have_image star9 spectrograph4)
       (have_image planet8 infrared1)
       (have_image star7 infrared0)
       (have_image phenomenon6 spectrograph4)
       (have_image planet5 infrared0))))