(define (problem pfile14) (:domain satellite)
  (:objects star24 planet23 star22 planet21 star20 star19 phenomenon18 planet17 planet16 planet15 star14 phenomenon13 phenomenon12 phenomenon11 star10 star9 planet8 phenomenon7 phenomenon6 phenomenon5 groundstation1 groundstation0 groundstation2 groundstation4 groundstation3 - direction
             thermograph0 image2 thermograph3 image1 thermograph4 - mode
             instrument2 instrument1 instrument0 - instrument
             satellite0 - satellite
            )
  (:init
       (supports instrument0 thermograph0)
       (supports instrument0 image1)
       (calibration_target instrument0 groundstation2)
       (supports instrument1 image2)
       (supports instrument1 thermograph3)
       (calibration_target instrument1 groundstation0)
       (supports instrument2 image1)
       (supports instrument2 thermograph3)
       (supports instrument2 thermograph4)
       (calibration_target instrument2 groundstation2)
       (on_board instrument0 satellite0)
       (on_board instrument1 satellite0)
       (on_board instrument2 satellite0)
       (power_avail satellite0)
       (pointing satellite0 phenomenon12))
  (:goal (and 
       (have_image planet23 image1)
       (have_image star22 thermograph3)
       (have_image planet21 thermograph0)
       (have_image star20 thermograph4)
       (have_image star19 thermograph4)
       (have_image phenomenon18 image1)
       (have_image planet17 image2)
       (have_image planet15 image2)
       (have_image star14 thermograph4)
       (have_image phenomenon13 image1)
       (have_image phenomenon12 thermograph0)
       (have_image star10 thermograph3)
       (have_image star9 thermograph0)
       (have_image planet8 image2)
       (have_image phenomenon7 thermograph0)
       (have_image phenomenon5 image1)
       (pointing satellite0 planet21))))