(define (problem pfile12) (:domain satellite)
  (:objects phenomenon24 star23 star22 phenomenon21 planet20 star19 star18 phenomenon17 planet16 star15 star14 phenomenon13 star12 planet11 planet10 star9 planet8 star7 phenomenon6 planet5 star4 star2 groundstation1 star3 star0 - direction
             infrared3 spectrograph4 infrared1 infrared0 thermograph2 - mode
             instrument4 instrument3 - instrument
             satellite1 - satellite
            )
  (:init
       (supports instrument3 infrared0)
       (supports instrument3 spectrograph4)
       (calibration_target instrument3 star4)
       (supports instrument4 infrared0)
       (supports instrument4 infrared3)
       (supports instrument4 thermograph2)
       (calibration_target instrument4 star4)
       (on_board instrument3 satellite1)
       (on_board instrument4 satellite1)
       (power_avail satellite1)
       (pointing satellite1 star4))
  (:goal (and 
       (have_image phenomenon24 infrared0)
       (have_image star23 spectrograph4)
       (have_image phenomenon21 thermograph2)
       (have_image planet20 thermograph2)
       (have_image star19 thermograph2)
       (have_image star18 spectrograph4)
       (have_image phenomenon17 spectrograph4)
       (have_image star15 infrared3)
       (have_image star14 thermograph2)
       (have_image phenomenon13 spectrograph4)
       (have_image planet11 infrared3)
       (have_image planet10 thermograph2)
       (have_image star9 spectrograph4)
       (have_image star7 infrared0)
       (have_image phenomenon6 spectrograph4)
       (have_image planet5 infrared0))))