(define (problem ipc3-pfile05) (:domain rover)
  (:objects objective0 objective1 objective2 - objective
             camera2 - camera
             waypoint0 waypoint1 waypoint2 waypoint3 - waypoint
             rover0store - store
             rover0 - rover
             colour high_res low_res - mode
             general - lander
            )
  (:init
       (visible waypoint0 waypoint2)
       (visible waypoint2 waypoint0)
       (visible waypoint1 waypoint0)
       (visible waypoint0 waypoint1)
       (visible waypoint1 waypoint3)
       (visible waypoint3 waypoint1)
       (visible waypoint2 waypoint1)
       (visible waypoint1 waypoint2)
       (visible waypoint3 waypoint0)
       (visible waypoint0 waypoint3)
       (visible waypoint3 waypoint2)
       (visible waypoint2 waypoint3)
       (at_rock_sample waypoint0)
       (at_soil_sample waypoint1)
       (at_rock_sample waypoint1)
       (at_soil_sample waypoint2)
       (at_soil_sample waypoint3)
       (at_lander general waypoint3)
       (channel_free general)
       (at rover0 waypoint0)
       (available rover0)
       (store_of rover0store rover0)
       (empty rover0store)
       (equipped_for_rock_analysis rover0)
       (equipped_for_imaging rover0)
       (can_traverse rover0 waypoint0 waypoint1)
       (can_traverse rover0 waypoint1 waypoint0)
       (can_traverse rover0 waypoint0 waypoint3)
       (can_traverse rover0 waypoint3 waypoint0)
       (on_board camera2 rover0)
       (calibration_target camera2 objective1)
       (supports camera2 colour)
       (supports camera2 high_res)
       (supports camera2 low_res)
       (visible_from objective0 waypoint0)
       (visible_from objective0 waypoint1)
       (visible_from objective0 waypoint2)
       (visible_from objective0 waypoint3)
       (visible_from objective1 waypoint0)
       (visible_from objective1 waypoint1)
       (visible_from objective1 waypoint2)
       (visible_from objective2 waypoint0)
       (visible_from objective2 waypoint1)
       (visible_from objective2 waypoint2))
  (:goal (and 
       (communicated_image_data objective0 colour)
       (communicated_image_data objective2 high_res)
       (communicated_image_data objective0 high_res)
       (communicated_rock_data waypoint1)
       (communicated_rock_data waypoint0))))