(define (problem ipc3-pfile13) (:domain rover)
  (:objects objective0 objective1 objective2 objective3 - objective
             camera3 - camera
             waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 - waypoint
             rover1store - store
             rover1 - rover
             colour high_res low_res - mode
             general - lander
            )
  (:init
       (visible waypoint0 waypoint1)
       (visible waypoint1 waypoint0)
       (visible waypoint0 waypoint3)
       (visible waypoint3 waypoint0)
       (visible waypoint0 waypoint5)
       (visible waypoint5 waypoint0)
       (visible waypoint0 waypoint6)
       (visible waypoint6 waypoint0)
       (visible waypoint1 waypoint2)
       (visible waypoint2 waypoint1)
       (visible waypoint1 waypoint3)
       (visible waypoint3 waypoint1)
       (visible waypoint1 waypoint4)
       (visible waypoint4 waypoint1)
       (visible waypoint1 waypoint5)
       (visible waypoint5 waypoint1)
       (visible waypoint1 waypoint7)
       (visible waypoint7 waypoint1)
       (visible waypoint1 waypoint8)
       (visible waypoint8 waypoint1)
       (visible waypoint2 waypoint0)
       (visible waypoint0 waypoint2)
       (visible waypoint2 waypoint4)
       (visible waypoint4 waypoint2)
       (visible waypoint2 waypoint6)
       (visible waypoint6 waypoint2)
       (visible waypoint3 waypoint4)
       (visible waypoint4 waypoint3)
       (visible waypoint3 waypoint7)
       (visible waypoint7 waypoint3)
       (visible waypoint4 waypoint0)
       (visible waypoint0 waypoint4)
       (visible waypoint5 waypoint2)
       (visible waypoint2 waypoint5)
       (visible waypoint5 waypoint3)
       (visible waypoint3 waypoint5)
       (visible waypoint7 waypoint0)
       (visible waypoint0 waypoint7)
       (visible waypoint7 waypoint2)
       (visible waypoint2 waypoint7)
       (visible waypoint7 waypoint6)
       (visible waypoint6 waypoint7)
       (visible waypoint8 waypoint2)
       (visible waypoint2 waypoint8)
       (visible waypoint8 waypoint3)
       (visible waypoint3 waypoint8)
       (visible waypoint8 waypoint4)
       (visible waypoint4 waypoint8)
       (visible waypoint8 waypoint7)
       (visible waypoint7 waypoint8)
       (at_rock_sample waypoint0)
       (at_rock_sample waypoint1)
       (at_soil_sample waypoint2)
       (at_rock_sample waypoint2)
       (at_soil_sample waypoint4)
       (at_rock_sample waypoint4)
       (at_soil_sample waypoint5)
       (at_rock_sample waypoint6)
       (at_soil_sample waypoint7)
       (at_rock_sample waypoint7)
       (at_rock_sample waypoint8)
       (at_lander general waypoint2)
       (channel_free general)
       (at rover1 waypoint6)
       (available rover1)
       (store_of rover1store rover1)
       (empty rover1store)
       (equipped_for_soil_analysis rover1)
       (equipped_for_imaging rover1)
       (can_traverse rover1 waypoint6 waypoint0)
       (can_traverse rover1 waypoint0 waypoint6)
       (can_traverse rover1 waypoint0 waypoint2)
       (can_traverse rover1 waypoint2 waypoint0)
       (can_traverse rover1 waypoint0 waypoint3)
       (can_traverse rover1 waypoint3 waypoint0)
       (can_traverse rover1 waypoint0 waypoint7)
       (can_traverse rover1 waypoint7 waypoint0)
       (can_traverse rover1 waypoint2 waypoint4)
       (can_traverse rover1 waypoint4 waypoint2)
       (can_traverse rover1 waypoint2 waypoint8)
       (can_traverse rover1 waypoint8 waypoint2)
       (can_traverse rover1 waypoint3 waypoint1)
       (can_traverse rover1 waypoint1 waypoint3)
       (on_board camera3 rover1)
       (calibration_target camera3 objective2)
       (supports camera3 colour)
       (supports camera3 low_res)
       (visible_from objective0 waypoint0)
       (visible_from objective1 waypoint0)
       (visible_from objective1 waypoint1)
       (visible_from objective1 waypoint2)
       (visible_from objective1 waypoint3)
       (visible_from objective1 waypoint4)
       (visible_from objective1 waypoint5)
       (visible_from objective1 waypoint6)
       (visible_from objective1 waypoint7)
       (visible_from objective2 waypoint0)
       (visible_from objective2 waypoint1)
       (visible_from objective2 waypoint2)
       (visible_from objective2 waypoint3)
       (visible_from objective2 waypoint4)
       (visible_from objective2 waypoint5)
       (visible_from objective3 waypoint0)
       (visible_from objective3 waypoint1)
       (visible_from objective3 waypoint2)
       (visible_from objective3 waypoint3)
       (visible_from objective3 waypoint4)
       (visible_from objective3 waypoint5)
       (visible_from objective3 waypoint6)
       (visible_from objective3 waypoint7))
  (:goal (and 
       (communicated_soil_data waypoint4)
       (communicated_soil_data waypoint2)
       (communicated_soil_data waypoint7))))