(define (problem ipc3-pfile12) (:domain rover)
  (:objects objective0 objective1 objective2 objective3 - objective
             camera1 - camera
             waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 - waypoint
             rover2store - store
             rover2 - rover
             colour high_res low_res - mode
             general - lander
            )
  (:init
       (visible waypoint0 waypoint1)
       (visible waypoint1 waypoint0)
       (visible waypoint0 waypoint3)
       (visible waypoint3 waypoint0)
       (visible waypoint0 waypoint5)
       (visible waypoint5 waypoint0)
       (visible waypoint0 waypoint6)
       (visible waypoint6 waypoint0)
       (visible waypoint0 waypoint7)
       (visible waypoint7 waypoint0)
       (visible waypoint1 waypoint5)
       (visible waypoint5 waypoint1)
       (visible waypoint1 waypoint7)
       (visible waypoint7 waypoint1)
       (visible waypoint2 waypoint0)
       (visible waypoint0 waypoint2)
       (visible waypoint2 waypoint5)
       (visible waypoint5 waypoint2)
       (visible waypoint3 waypoint2)
       (visible waypoint2 waypoint3)
       (visible waypoint3 waypoint7)
       (visible waypoint7 waypoint3)
       (visible waypoint4 waypoint2)
       (visible waypoint2 waypoint4)
       (visible waypoint4 waypoint5)
       (visible waypoint5 waypoint4)
       (visible waypoint4 waypoint6)
       (visible waypoint6 waypoint4)
       (visible waypoint5 waypoint3)
       (visible waypoint3 waypoint5)
       (visible waypoint6 waypoint5)
       (visible waypoint5 waypoint6)
       (visible waypoint6 waypoint7)
       (visible waypoint7 waypoint6)
       (visible waypoint7 waypoint2)
       (visible waypoint2 waypoint7)
       (visible waypoint7 waypoint4)
       (visible waypoint4 waypoint7)
       (visible waypoint7 waypoint5)
       (visible waypoint5 waypoint7)
       (at_soil_sample waypoint0)
       (at_rock_sample waypoint0)
       (at_rock_sample waypoint2)
       (at_rock_sample waypoint3)
       (at_rock_sample waypoint5)
       (at_rock_sample waypoint6)
       (at_rock_sample waypoint7)
       (at_lander general waypoint2)
       (channel_free general)
       (at rover2 waypoint7)
       (available rover2)
       (store_of rover2store rover2)
       (empty rover2store)
       (equipped_for_soil_analysis rover2)
       (equipped_for_imaging rover2)
       (can_traverse rover2 waypoint7 waypoint0)
       (can_traverse rover2 waypoint0 waypoint7)
       (can_traverse rover2 waypoint7 waypoint1)
       (can_traverse rover2 waypoint1 waypoint7)
       (can_traverse rover2 waypoint7 waypoint2)
       (can_traverse rover2 waypoint2 waypoint7)
       (can_traverse rover2 waypoint7 waypoint3)
       (can_traverse rover2 waypoint3 waypoint7)
       (can_traverse rover2 waypoint7 waypoint5)
       (can_traverse rover2 waypoint5 waypoint7)
       (can_traverse rover2 waypoint7 waypoint6)
       (can_traverse rover2 waypoint6 waypoint7)
       (on_board camera1 rover2)
       (calibration_target camera1 objective1)
       (supports camera1 high_res)
       (visible_from objective0 waypoint0)
       (visible_from objective0 waypoint1)
       (visible_from objective0 waypoint2)
       (visible_from objective1 waypoint0)
       (visible_from objective1 waypoint1)
       (visible_from objective1 waypoint2)
       (visible_from objective1 waypoint3)
       (visible_from objective2 waypoint0)
       (visible_from objective2 waypoint1)
       (visible_from objective2 waypoint2)
       (visible_from objective2 waypoint3)
       (visible_from objective2 waypoint4)
       (visible_from objective3 waypoint0)
       (visible_from objective3 waypoint1)
       (visible_from objective3 waypoint2)
       (visible_from objective3 waypoint3)
       (visible_from objective3 waypoint4)
       (visible_from objective3 waypoint5))
  (:goal (and 
       (communicated_image_data objective1 high_res)
       (communicated_soil_data waypoint0))))