(define (problem ipc3-pfile07) (:domain rover)
  (:objects objective0 objective1 - objective
             waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 - waypoint
             rover1store - store
             rover1 - rover
             colour high_res low_res - mode
             general - lander
            )
  (:init
       (visible waypoint0 waypoint3)
       (visible waypoint3 waypoint0)
       (visible waypoint0 waypoint5)
       (visible waypoint5 waypoint0)
       (visible waypoint1 waypoint0)
       (visible waypoint0 waypoint1)
       (visible waypoint2 waypoint0)
       (visible waypoint0 waypoint2)
       (visible waypoint2 waypoint1)
       (visible waypoint1 waypoint2)
       (visible waypoint2 waypoint5)
       (visible waypoint5 waypoint2)
       (visible waypoint3 waypoint2)
       (visible waypoint2 waypoint3)
       (visible waypoint4 waypoint0)
       (visible waypoint0 waypoint4)
       (visible waypoint4 waypoint3)
       (visible waypoint3 waypoint4)
       (visible waypoint5 waypoint1)
       (visible waypoint1 waypoint5)
       (visible waypoint5 waypoint4)
       (visible waypoint4 waypoint5)
       (at_soil_sample waypoint1)
       (at_rock_sample waypoint2)
       (at_rock_sample waypoint3)
       (at_soil_sample waypoint4)
       (at_rock_sample waypoint4)
       (at_rock_sample waypoint5)
       (at_lander general waypoint3)
       (channel_free general)
       (at rover1 waypoint3)
       (available rover1)
       (store_of rover1store rover1)
       (empty rover1store)
       (equipped_for_rock_analysis rover1)
       (can_traverse rover1 waypoint3 waypoint0)
       (can_traverse rover1 waypoint0 waypoint3)
       (can_traverse rover1 waypoint3 waypoint2)
       (can_traverse rover1 waypoint2 waypoint3)
       (can_traverse rover1 waypoint3 waypoint4)
       (can_traverse rover1 waypoint4 waypoint3)
       (can_traverse rover1 waypoint0 waypoint1)
       (can_traverse rover1 waypoint1 waypoint0)
       (can_traverse rover1 waypoint0 waypoint5)
       (can_traverse rover1 waypoint5 waypoint0)
       (visible_from objective0 waypoint0)
       (visible_from objective0 waypoint1)
       (visible_from objective0 waypoint2)
       (visible_from objective0 waypoint3)
       (visible_from objective0 waypoint4)
       (visible_from objective1 waypoint0)
       (visible_from objective1 waypoint1)
       (visible_from objective1 waypoint2)
       (visible_from objective1 waypoint3))
  (:goal (and 
       (communicated_rock_data waypoint4)
       (communicated_rock_data waypoint2)
       (communicated_rock_data waypoint3))))