#!/bin/sh 

#Configuration for CoDMAP optimizating time and coverage, CMAP
./run-map.sh -d $1 -p $2 -o $3 -A cmap -s mingoals -P public -M nil  -a lama-unit-cost -r lama-unit-cost -g subsets -y nil -Y lama-second -t 1800 -C t

#Configuration for CoDMAP optimizating quality and coverage, CMAP
#./run-map.sh -d $1 -p $2 -o $3 -A cmap -s mingoals -P public -M nil  -a lama-unit-cost -r lama-unit-cost -g subsets -y t -Y lama-second -t 1800 -C t

#Configuration for CoDMAP optimizating privacity, MAPR, makespan, unitcost, macros and only-one-macro
#./run-map.sh -d $1 -p $2 -o $3 -A mapr -s subgoals -P public -M nil  -a lama-unit-cost -r lama-unit-cost -g rest-achievable -y nil -Y lama-second -t 1800 -C t  -O t -u t 


