(define (problem nil) (:domain port)
  (:objects ship1 ship0 - ship
             dock0 - dock
             pallet34 pallet33 pallet32 pallet31 pallet30 pallet29 pallet28 pallet27 pallet26 pallet25 pallet24 pallet23 pallet22 pallet21 pallet20 pallet19 pallet18 pallet17 pallet16 pallet15 - pallet-ship
             pallet14 pallet13 pallet12 pallet11 pallet10 pallet9 pallet8 pallet7 pallet6 pallet5 pallet4 pallet3 pallet2 pallet1 pallet0 - pallet-dock
             crate29 crate28 crate27 crate26 crate25 crate24 crate23 crate22 crate21 crate20 crate19 crate18 crate17 crate16 crate15 crate14 crate13 crate12 crate11 crate10 crate9 crate8 crate7 crate6 crate5 crate4 crate3 crate2 crate1 crate0 - crate
             level3 level2 level1 level0 - level
             hoist1 hoist0 - hoist
            )
  (:init
       (clear pallet15)
       (clear pallet16)
       (clear pallet17)
       (clear pallet18)
       (clear pallet19)
       (clear pallet20)
       (clear pallet21)
       (clear pallet22)
       (clear pallet23)
       (clear pallet24)
       (clear pallet25)
       (clear pallet26)
       (clear pallet27)
       (clear pallet28)
       (clear pallet29)
       (clear pallet30)
       (clear pallet31)
       (clear pallet32)
       (clear pallet33)
       (clear pallet34)
       (clear crate0)
       (clear crate25)
       (clear crate26)
       (clear crate21)
       (clear crate27)
       (clear crate7)
       (clear crate14)
       (clear crate9)
       (clear crate16)
       (clear crate11)
       (clear pallet10)
       (clear crate29)
       (clear crate24)
       (clear crate23)
       (clear crate28)
       (height crate29 level2)
       (on-dock crate29 crate13)
       (at crate29 dock0)
       (height crate28 level2)
       (on-dock crate28 crate3)
       (at crate28 dock0)
       (height crate27 level3)
       (on-dock crate27 crate18)
       (at crate27 dock0)
       (height crate26 level2)
       (on-dock crate26 crate22)
       (at crate26 dock0)
       (height crate25 level2)
       (on-dock crate25 crate5)
       (at crate25 dock0)
       (height crate24 level3)
       (on-dock crate24 crate20)
       (at crate24 dock0)
       (height crate23 level3)
       (on-dock crate23 crate19)
       (at crate23 dock0)
       (height crate22 level1)
       (on-dock crate22 pallet2)
       (at crate22 dock0)
       (height crate21 level3)
       (on-dock crate21 crate12)
       (at crate21 dock0)
       (height crate20 level2)
       (on-dock crate20 crate15)
       (at crate20 dock0)
       (height crate19 level2)
       (on-dock crate19 crate17)
       (at crate19 dock0)
       (height crate18 level2)
       (on-dock crate18 crate4)
       (at crate18 dock0)
       (height crate17 level1)
       (on-dock crate17 pallet13)
       (at crate17 dock0)
       (height crate16 level3)
       (on-dock crate16 crate6)
       (at crate16 dock0)
       (height crate15 level1)
       (on-dock crate15 pallet12)
       (at crate15 dock0)
       (height crate14 level1)
       (on-dock crate14 pallet6)
       (at crate14 dock0)
       (height crate13 level1)
       (on-dock crate13 pallet11)
       (at crate13 dock0)
       (height crate12 level2)
       (on-dock crate12 crate10)
       (at crate12 dock0)
       (height crate11 level1)
       (on-dock crate11 pallet9)
       (at crate11 dock0)
       (height crate10 level1)
       (on-dock crate10 pallet3)
       (at crate10 dock0)
       (height crate9 level3)
       (on-dock crate9 crate8)
       (at crate9 dock0)
       (height crate8 level2)
       (on-dock crate8 crate1)
       (at crate8 dock0)
       (height crate7 level1)
       (on-dock crate7 pallet5)
       (at crate7 dock0)
       (height crate6 level2)
       (on-dock crate6 crate2)
       (at crate6 dock0)
       (height crate5 level1)
       (on-dock crate5 pallet1)
       (at crate5 dock0)
       (height crate4 level1)
       (on-dock crate4 pallet4)
       (at crate4 dock0)
       (height crate3 level1)
       (on-dock crate3 pallet14)
       (at crate3 dock0)
       (height crate2 level1)
       (on-dock crate2 pallet8)
       (at crate2 dock0)
       (height crate1 level1)
       (on-dock crate1 pallet7)
       (at crate1 dock0)
       (height crate0 level1)
       (on-dock crate0 pallet0)
       (at crate0 dock0)
       (height pallet34 level0)
       (at pallet34 ship1)
       (height pallet33 level0)
       (at pallet33 ship1)
       (height pallet32 level0)
       (at pallet32 ship1)
       (height pallet31 level0)
       (at pallet31 ship1)
       (height pallet30 level0)
       (at pallet30 ship1)
       (height pallet29 level0)
       (at pallet29 ship1)
       (height pallet28 level0)
       (at pallet28 ship1)
       (height pallet27 level0)
       (at pallet27 ship1)
       (height pallet26 level0)
       (at pallet26 ship1)
       (height pallet25 level0)
       (at pallet25 ship1)
       (available hoist1)
       (assigned hoist1 ship1)
       (height pallet24 level0)
       (at pallet24 ship0)
       (height pallet23 level0)
       (at pallet23 ship0)
       (height pallet22 level0)
       (at pallet22 ship0)
       (height pallet21 level0)
       (at pallet21 ship0)
       (height pallet20 level0)
       (at pallet20 ship0)
       (height pallet19 level0)
       (at pallet19 ship0)
       (height pallet18 level0)
       (at pallet18 ship0)
       (height pallet17 level0)
       (at pallet17 ship0)
       (height pallet16 level0)
       (at pallet16 ship0)
       (height pallet15 level0)
       (at pallet15 ship0)
       (available hoist0)
       (assigned hoist0 ship0)
       (height pallet14 level0)
       (at pallet14 dock0)
       (height pallet13 level0)
       (at pallet13 dock0)
       (height pallet12 level0)
       (at pallet12 dock0)
       (height pallet11 level0)
       (at pallet11 dock0)
       (height pallet10 level0)
       (at pallet10 dock0)
       (height pallet9 level0)
       (at pallet9 dock0)
       (height pallet8 level0)
       (at pallet8 dock0)
       (height pallet7 level0)
       (at pallet7 dock0)
       (height pallet6 level0)
       (at pallet6 dock0)
       (height pallet5 level0)
       (at pallet5 dock0)
       (height pallet4 level0)
       (at pallet4 dock0)
       (height pallet3 level0)
       (at pallet3 dock0)
       (height pallet2 level0)
       (at pallet2 dock0)
       (height pallet1 level0)
       (at pallet1 dock0)
       (height pallet0 level0)
       (at pallet0 dock0)
       (next level2 level3)
       (next level1 level2)
       (next level0 level1))
  (:goal (and 
       (on-ship crate29 crate10 ship0)
       (on-ship crate28 pallet26 ship1)
       (on-ship crate27 pallet19 ship0)
       (on-ship crate26 crate5 ship1)
       (on-ship crate25 crate15 ship0)
       (on-ship crate24 pallet15 ship0)
       (on-ship crate23 crate21 ship1)
       (on-ship crate22 crate20 ship0)
       (on-ship crate21 crate17 ship1)
       (on-ship crate20 crate6 ship0)
       (on-ship crate19 crate18 ship1)
       (on-ship crate18 crate8 ship1)
       (on-ship crate17 pallet32 ship1)
       (on-ship crate16 crate4 ship1)
       (on-ship crate15 pallet22 ship0)
       (on-ship crate14 crate12 ship1)
       (on-ship crate13 pallet33 ship1)
       (on-ship crate12 crate7 ship1)
       (on-ship crate11 crate9 ship1)
       (on-ship crate10 pallet16 ship0)
       (on-ship crate9 crate1 ship1)
       (on-ship crate8 pallet28 ship1)
       (on-ship crate7 pallet31 ship1)
       (on-ship crate6 pallet24 ship0)
       (on-ship crate5 crate0 ship1)
       (on-ship crate4 crate3 ship1)
       (on-ship crate3 pallet34 ship1)
       (on-ship crate2 pallet20 ship0)
       (on-ship crate1 pallet30 ship1)
       (on-ship crate0 pallet29 ship1))))