(define (problem BLOCKS-6-2)
(:domain  ma-blocksworld)
(:objects  r0 r1 r2 r3 r4 r5 r6 r7 r8 r9 r10 - robot E F B D C A - block)
(:INIT (HANDEMPTY r0) (HANDEMPTY r1) (HANDEMPTY r2) (HANDEMPTY r3) (HANDEMPTY r4) (HANDEMPTY r5) (HANDEMPTY r6) (HANDEMPTY r7) (HANDEMPTY r8) (HANDEMPTY r9) (HANDEMPTY r10) (CLEAR A) (ONTABLE C) (ON A D) (ON D B) (ON B F) (ON F E) (ON E C)
)
(:goal (AND (ON E F) (ON F A) (ON A B) (ON B C) (ON C D)))
)
