#!/bin/bash

planners=( "arvand" "lama-2008" "lpgn" "preprocess-old" "randward" "search" "preprocess")

cd "$(dirname "$0")"
ROOT=$PWD


for item in ${planners[*]}
do
	planner_path="$ROOT"/src/"$item"
	echo -e "\n**************************"
	echo "*** clean" $item "***" 
	echo -e "**************************\n"
	cd $planner_path
	pwd
	make clean
	make distclean

	if [ $? -ne 0 ]; then
		echo -e "\nError:" $item 
		exit 1
	fi

done

cd "$ROOT"
echo "----**** -----  End first part"
##parser
cd "$ROOT"/src/parser
rm -f *.pyc
cd adl2strips
make veryclean
cd ..
cd VAL-4.2.08
make clean
cd "$ROOT"
##launcher
cd "$ROOT"/src/launcher
rm -f *.pyc
cd "$ROOT"
##translate-old
cd "$ROOT"/src/translate-old
rm -f *.pyc
cd pddl
rm -f *.pyc
cd "$ROOT"
##translate
cd "$ROOT"/src/translate
rm -f *.pyc
cd pddl
rm -f *.pyc
cd "$ROOT"
##madagascar
cd "$ROOT"/src/madagascar/nplan
make clean
cd ..
cd nsat
make clean
cd "$ROOT"
##probe
cd "$ROOT"/src/probe
./clean_all
cd "$ROOT"
##yahsp2-mt
cd "$ROOT"/src/yahsp2-mt/src
make clean
make distclean
echo -e "\nEnd Clean"
